"""Generate the PowerSync AppSchema from the models and the tables in sync-rules.yaml."""

from __future__ import annotations

import re
from pathlib import Path

from sqlalchemy import BigInteger, Boolean, Float, Integer, Numeric, SmallInteger
from sqlalchemy.types import TypeEngine

from clientbridge import models  # noqa: F401  -- imported for its side effect: populates metadata
from clientbridge.core.db import Base

ROOT = Path(__file__).resolve().parents[2]  # backend/scripts/<file> → repo root
SYNC_RULES = ROOT / "infra" / "powersync" / "sync-rules.yaml"
OUT = ROOT / "frontend" / "packages" / "sync" / "src" / "schema.ts"

HEADER = """\
// AUTO-GENERATED by `make gen-sync-schema` from the backend SQLAlchemy models + sync-rules.yaml.
// Do NOT edit by hand — change the models (and infra/powersync/sync-rules.yaml), then regenerate.
// `id` is the implicit text PK; money = integer cents; json/arrays/timestamps stored as text.
import { column, Schema, Table } from "@powersync/common";
"""


# Device-only tables: kept in local SQLite, never uploaded or synced (recent searches, read marks).
LOCAL_ONLY = {
    "device_prefs": {"value": "text", "updated_at": "text"},
    "business_selection": {"business_id": "text"},
    "hours_outbox": {
        "business_id": "text",
        "staff_id": "text",
        "actor_id": "text",
        "payload": "text",
        "state": "text",
        "predecessor_id": "text",
        "result_revision": "integer",
        "attempt_count": "integer",
        "retry_at": "integer",
        "error_code": "text",
        "created_at": "text",
        "sequence": "integer",
    },
}


def gen_local_table(name: str, columns: dict[str, str]) -> str:
    cols = [f"        {col}: column.{kind}," for col, kind in columns.items()]
    return "\n".join(
        [f"const {name} = new Table(", "    {", *cols, "    },", "    { localOnly: true },", ");"]
    )


def synced_columns(rules: str | None = None) -> dict[str, list[str]]:
    """Union explicit data projections; reject syntax that could broaden the replica."""
    projections: dict[str, list[str]] = {}
    in_data = False
    for line in (SYNC_RULES.read_text() if rules is None else rules).splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if len(line) - len(line.lstrip()) <= 4:
            in_data = stripped == "data:"
            continue
        if not in_data:
            continue
        match = re.fullmatch(r"- SELECT (.+?) FROM (\w+)(?:\s+WHERE .+)?", stripped)
        if match is None:
            raise ValueError(f"Unsupported sync data projection: {stripped}")
        columns, table = match.groups()
        names = [column.strip() for column in columns.split(",")]
        if not names or any(re.fullmatch(r"[a-z_][a-z_0-9]*", n) is None for n in names):
            raise ValueError(f"Explicit column names required for {table}")
        if "id" not in names:
            raise ValueError(f"Missing replica id for {table}")
        for name in names:
            if name not in Base.metadata.tables[table].c:
                raise ValueError(f"Unknown replica column: {table}.{name}")
            if name not in projections.setdefault(table, []):
                projections[table].append(name)
    if not projections:
        raise ValueError("No sync data projections found")
    return projections


def synced_tables() -> list[str]:
    return list(synced_columns())


def ps_type(type_: TypeEngine[object]) -> str:
    """Map a SQLAlchemy column type to one of PowerSync's three client types."""
    if isinstance(type_, Boolean):
        return "integer"
    if isinstance(type_, BigInteger | SmallInteger | Integer):
        return "integer"
    if isinstance(type_, Numeric | Float):
        return "real"
    return "text"  # String/Text/Enum/DateTime/Date/Time/JSONB/ARRAY → text


def gen_table(name: str, projected: list[str]) -> str:
    table = Base.metadata.tables[name]
    cols = [
        f"        {col.name}: column.{ps_type(col.type)},"
        for col in table.columns
        if col.name != "id" and col.name in projected
    ]
    indexes = [
        f"            {re.sub(r'^ix_', '', idx.name or '')}: "
        f"[{', '.join(repr(c.name) for c in idx.columns)}],"
        for idx in sorted(table.indexes, key=lambda i: i.name or "")
        if idx.name and all(c.name in projected for c in idx.columns)
    ]

    out = [f"const {name} = new Table(", "    {", *cols, "    },"]
    if indexes:
        out += ["    {", "        indexes: {", *indexes, "        },", "    },"]
    out.append(");")
    return "\n".join(out)


def main() -> None:
    projections = synced_columns()
    names = list(projections)
    body = "\n\n".join(
        [
            *(gen_table(n, projections[n]) for n in names),
            *(gen_local_table(n, c) for n, c in LOCAL_ONLY.items()),
        ]
    )
    members = ",\n".join(f"    {n}" for n in [*names, *LOCAL_ONLY])
    content = (
        f"{HEADER}\n"
        f"{body}\n\n"
        f"export const AppSchema = new Schema({{\n{members},\n}});\n\n"
        f'export type Database = (typeof AppSchema)["types"];\n'
    )
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(names)} synced tables)")


if __name__ == "__main__":
    main()
