"""Generate the PowerSync client AppSchema (TypeScript) from the backend models + sync-rules.

Single source of truth = the SQLAlchemy models. The set of *synced* tables is read from
``infra/powersync/sync-rules.yaml`` (every ``FROM <table>``); each table's columns + types come
from the model metadata. Output: ``frontend/packages/sync/src/schema.ts``.

Run: ``make gen-sync-schema`` (regenerates, then prettifies).
"""

from __future__ import annotations

import re
from pathlib import Path

from sqlalchemy import BigInteger, Boolean, Float, Integer, Numeric, SmallInteger
from sqlalchemy.types import TypeEngine

from clientbridge import models  # noqa: F401  -- imported for its side effect: populates metadata
from clientbridge.core.db import Base

ROOT = Path(__file__).resolve().parents[2]  # backend/scripts/<file> → repo root
SYNC_RULES = ROOT / "infra" / "powersync" / "sync-rules.yaml"
OUT = ROOT / "frontend" / "packages" / "sync" / "src" / "schema.ts"

HEADER = """\
// AUTO-GENERATED by `make gen-sync-schema` from the backend SQLAlchemy models + sync-rules.yaml.
// Do NOT edit by hand — change the models (and infra/powersync/sync-rules.yaml), then regenerate.
// `id` is the implicit text PK; money = integer cents; json/arrays/timestamps stored as text.
import { column, Schema, Table } from "@powersync/common";
"""


def synced_tables() -> list[str]:
    """Table names appearing in any `FROM <table>` clause of the sync rules, in first-seen order."""
    text = SYNC_RULES.read_text()
    ordered: list[str] = []
    for match in re.finditer(r"FROM\s+(\w+)", text):
        name = match.group(1)
        if name not in ordered:
            ordered.append(name)
    return ordered


def ps_type(type_: TypeEngine[object]) -> str:
    """Map a SQLAlchemy column type to one of PowerSync's three client types."""
    if isinstance(type_, Boolean):
        return "integer"
    if isinstance(type_, BigInteger | SmallInteger | Integer):
        return "integer"
    if isinstance(type_, Numeric | Float):
        return "real"
    return "text"  # String/Text/Enum/DateTime/Date/Time/JSONB/ARRAY → text


def gen_table(name: str) -> str:
    table = Base.metadata.tables[name]
    cols = [
        f"        {col.name}: column.{ps_type(col.type)},"
        for col in table.columns
        if col.name != "id"
    ]
    indexes = [
        f"            {re.sub(r'^ix_', '', idx.name or '')}: "
        f"[{', '.join(repr(c.name) for c in idx.columns)}],"
        for idx in sorted(table.indexes, key=lambda i: i.name or "")
        if idx.name
    ]

    out = [f"const {name} = new Table(", "    {", *cols, "    },"]
    if indexes:
        out += ["    {", "        indexes: {", *indexes, "        },", "    },"]
    out.append(");")
    return "\n".join(out)


def main() -> None:
    names = [t for t in synced_tables() if t in Base.metadata.tables]
    body = "\n\n".join(gen_table(n) for n in names)
    members = ",\n".join(f"    {n}" for n in names)
    content = (
        f"{HEADER}\n"
        f"{body}\n\n"
        f"export const AppSchema = new Schema({{\n{members},\n}});\n\n"
        f'export type Database = (typeof AppSchema)["types"];\n'
    )
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(names)} synced tables)")


if __name__ == "__main__":
    main()
