// Every user-facing string, shared by web and mobile.

export const strings = {
    common: {
        appName: "Clientbridge",
        somethingWrongRetry: "Something went wrong. Please try again.",
        fileUploadError: "Couldn't upload that file. Please try again.",
        loading: "Loading…",
        saved: "Saved.",
        save: "Save changes",
        saving: "Saving…",
        cancel: "Cancel",
        done: "Done",
        close: "Close",
        somethingWrong: "Something went wrong",
        tryAgainLater: "Please try again later.",
        working: "Working…",
        busyEllipsis: "…",
        optional: "(optional)",
        decrease: (label: string) => `Decrease ${label}`,
        increase: (label: string) => `Increase ${label}`,
        stars: (n: number) => `${n} star${n === 1 ? "" : "s"}`,
        ratingOf: (n: number) => `${n} out of 5`,
        stillSyncing: "Still syncing — try again in a moment.",
        today: "Today",
        yesterday: "Yesterday",
        tomorrow: "Tomorrow",
        relativeTime: {
            justNow: "just now",
            minutes: (n: number) => `${n}m`,
            hours: (n: number) => `${n}h`,
            days: (n: number) => `${n}d`,
        },
    },
    ui: {
        clearSearch: "Clear search",
        clear: "Clear",
        copy: "Copy",
        copied: "Copied",
        remove: "Remove",
        removeTag: (tag: string) => `Remove ${tag}`,
        createTag: (text: string) => `Add "${text}"`,
        previous: "Previous",
        next: "Next",
        done: "(done)",
        withCount: (label: string, count: string) => `${label}, ${count}`,
        onTicket: (name: string, count: number) => `${name}, ${count} on ticket`,
        startOf: (day: string) => `${day} start`,
        endOf: (day: string) => `${day} end`,
        cardFallback: "CARD",
        listError: "This list didn't load.",
        listErrorBody: "Check your connection, then try again.",
        retry: "Try again",
        retrying: "Trying…",
        searchOptions: "Search",
        noMatches: "Nothing matches.",
        loadFailed: "This didn't load.",
        loadFailedBody: "Check your connection and try again. Nothing you saved is lost.",
    },
    billing: {
        invoices: "Invoices",
        estimates: "Estimates",
        invoiceNo: (n: number) => `Invoice #${n}`,
        estimateNo: (n: number) => `Estimate #${n}`,
        draftInvoice: "Draft invoice",
        draftEstimate: "Draft estimate",
        number: (n: number) => `#${n}`,
        newInvoice: "New invoice",
        newEstimate: "New estimate",
        dash: "—",
        search: "Search client or number",
        subtotal: "Subtotal",
        total: "Total",
        balanceDue: "Balance due",
        depositApplied: "Deposit applied",
        paymentOn: (method: string, when: string) => `${method}, ${when}`,
        taxRow: (code: string, pct: string) => `${code} ${pct}`,
        lines: "Lines",
        qtyTimes: (qty: number, price: string) => `${qty} × ${price}`,
        notes: "Notes",
        history: "History",
        payments: "Payments",
        payLink: "Pay link",
        acceptLink: "Client link",
        copyLink: "Copy link",
        copied: "Copied",
        pdf: "PDF",
        edit: "Edit",
        colNumber: "Number",
        colClient: "Client",
        colIssued: "Issued",
        colDue: "Due",
        colValid: "Valid until",
        colStatus: "Status",
        colTotal: "Total",
        colBalance: "Balance",
        loadingInvoices: "Loading invoices",
        loadingEstimates: "Loading estimates",
        loadError: "Couldn't load invoices",
        loadErrorEstimates: "Couldn't load estimates",
        statusLabel: {
            draft: "Draft",
            sent: "Sent",
            partial: "Partly paid",
            overdue: "Overdue",
            paid: "Paid",
            refunded: "Refunded",
            void: "Void",
        } as Record<string, string>,
        dueOn: (when: string) => `Due ${when}`,
        dueToday: "Due today",
        overdueBy: (days: number) => `${days} ${days === 1 ? "day" : "days"} overdue`,
        paidOn: (when: string) => `Paid ${when}`,
        voidedOn: (when: string) => `Voided ${when}`,
        notSent: "Not sent",
        segments: {
            all: "All",
            open: "Open",
            overdue: "Overdue",
            draft: "Drafts",
            paid: "Paid",
            void: "Void",
        },
        segmentCount: (label: string, n: number) => `${label} ${n}`,
        statOutstanding: "Outstanding",
        statOutstandingHint: (n: number) =>
            `${n} ${n === 1 ? "invoice" : "invoices"} awaiting payment`,
        statOverdue: "Overdue",
        statOverdueHint: (n: number) =>
            n === 0 ? "Nothing overdue" : `${n} ${n === 1 ? "invoice" : "invoices"} past due`,
        statPaid: "Paid, last 30 days",
        statPaidHint: (n: number) => `${n} ${n === 1 ? "invoice" : "invoices"} settled`,
        statDrafts: "Drafts",
        statDraftsHint: (n: number) =>
            n === 0 ? "Nothing waiting" : `${n} ${n === 1 ? "draft" : "drafts"} to send`,
        summary: (n: number, owed: string) =>
            `${n} ${n === 1 ? "invoice" : "invoices"} · ${owed} outstanding`,
        estimatesSummary: (n: number, open: string) =>
            `${n} ${n === 1 ? "estimate" : "estimates"} · ${open} waiting on clients`,
        emptyInvoicesTitle: "No invoices yet",
        emptyInvoicesBody: "Invoice a client from a completed booking, or start one here.",
        emptySegment: (label: string) => `No ${label.toLowerCase()} invoices.`,
        emptySearch: "Nothing matches that search.",
        emptyEstimatesTitle: "No estimates yet",
        emptyEstimatesBody:
            "Quote a job before you book it, and convert it to an invoice when it's accepted.",
        emptyEstimateSegment: (label: string) => `No ${label.toLowerCase()} estimates.`,
        send: "Send",
        sendInvoice: "Send invoice",
        remind: "Remind",
        recordPayment: "Record payment",
        void: "Void",
        voidConfirmTitle: (n: number) => `Void invoice #${n}?`,
        voidConfirmBody:
            "The client's pay link stops working and the amount comes off what they owe. This can't be undone.",
        voidDraftConfirmTitle: "Void this draft?",
        invoiceSentTo: (n: number, name: string) => `Invoice #${n} sent to ${name}.`,
        reminderSentTo: (name: string) => `Reminder sent to ${name}.`,
        invoiceVoided: (label: string) => `${label} voided. It stays in the list for your records.`,
        actionError: "Couldn't do that. Nothing changed; try again.",
        event: {
            created: "Created",
            sent: "Sent to the client",
            payment: (amount: string, method: string) => `Payment of ${amount}, ${method}`,
            depositApplied: (amount: string) => `Deposit of ${amount} applied`,
            refund: (amount: string) => `Refunded ${amount}`,
            voided: "Voided",
            accepted: "Accepted",
            declined: "Declined",
            converted: (n: string) => `Converted to invoice ${n}`,
        },
        method: {
            card: "Card",
            cash: "Cash",
            interac: "Interac e-Transfer",
            bank_eft: "Bank debit",
            cheque: "Cheque",
            other: "Other",
            deposit: "Booking deposit",
        } as Record<string, string>,
        paymentPending: "Processing",
        estimateStatus: {
            draft: "Draft",
            sent: "Sent",
            accepted: "Accepted",
            declined: "Declined",
            expired: "Expired",
            converted: "Converted",
        } as Record<string, string>,
        estimateSegments: {
            all: "All",
            draft: "Drafts",
            sent: "Waiting",
            accepted: "Accepted",
            closed: "Closed",
        },
        validUntil: (when: string) => `Valid until ${when}`,
        expiresIn: (days: number) =>
            days === 0 ? "Expires today" : `Expires in ${days} ${days === 1 ? "day" : "days"}`,
        expiredOn: (when: string) => `Expired ${when}`,
        acceptedOn: (when: string) => `Accepted ${when}`,
        declinedOn: (when: string) => `Declined ${when}`,
        convertedTo: (n: string) => `Invoice ${n}`,
        convert: "Convert to invoice",
        convertTitle: "Convert to invoice?",
        convertBody:
            "The invoice gets the same lines and tax, plus any add-ons the client picked. It starts as a draft you can edit before sending.",
        markAccepted: "Mark accepted",
        markDeclined: "Mark declined",
        sendEstimate: "Send estimate",
        declineReason: "Reason given",
        addOnPicked: "Add-on, picked by the client",
        addOnNotPicked: "Add-on, not picked",
        addOnOffered: "Optional add-on",
        estimateSentTo: (n: number, name: string) => `Estimate #${n} sent to ${name}.`,
        estimateMarkedAccepted: (label: string) => `${label} marked accepted.`,
        estimateMarkedDeclined: (label: string) => `${label} marked declined.`,
        convertedDraft: "Invoice created as a draft. Find it under Drafts.",
        client: "Client",
        chooseClient: "Choose a client",
        addFromCatalog: "Add from catalog",
        addCustomLine: "Custom line",
        description: "Description",
        descriptionPlaceholder: "Service or item",
        qty: "Qty",
        price: "Price",
        taxClass: "Tax",
        optional: "Optional add-on",
        optionalHint: "Starts unticked; the client can add it when accepting",
        removeLine: "Remove line",
        validFor: "Valid for",
        dueTerms: "Payment due",
        terms: {
            receipt: "On receipt",
            d7: "7 days",
            d14: "14 days",
            d30: "30 days",
        },
        messageToClient: "Message to client",
        messagePlaceholder: "Shown above the lines",
        saveDraft: "Save draft",
        saving: "Saving…",
        sending: "Sending…",
        livePreview: "Live preview",
        preview: "Preview",
        taxNote: (rates: string) => `Tax: ${rates}`,
        noTaxNote: "You don't collect sales tax yet, so nothing is added.",
        needClient: "Choose a client.",
        needLine: "Add at least one line with a price.",
        lineIncomplete: "Add a description and price.",
        saveError: "Couldn't save. Your lines are still here, try again.",
        sendError: "Couldn't send. Try again; nothing was sent twice.",
        draftSaved: "Draft saved. It stays in Drafts until you send it.",
        sentTitle: (noun: string) => `${noun} sent`,
        sentBody: (who: string) => `${who} gets it by email with a link to open it.`,
        startAnother: "Start another",
        discardTitle: "Close without saving?",
        discardBody: "Changes since the last save are lost.",
        discard: "Close",
        keepEditing: "Keep editing",
        rec: {
            title: "Record a payment",
            subtitle: (client: string, n: string) => `${client} · ${n}`,
            howPaid: "How did they pay?",
            savedCardHint: "Charge it now",
            noSavedCard: "Saved card",
            noSavedCardHint: "None on file for this client",
            reader: "Tap to Pay",
            readerHint: "Take it at the desk under Sales",
            cash: "Cash",
            cashHint: "Paid at the desk",
            etransfer: "e-Transfer received",
            etransferHint: "Already in your bank",
            cheque: "Cheque",
            chequeHint: "Record it once deposited",
            amount: "Amount",
            fullBalance: (amount: string) => `Full balance ${amount}`,
            partial: "Part of it",
            tendered: "Cash handed over",
            change: "Change to give",
            noChange: "Exact amount",
            reference: "Interac reference",
            referenceHint: "From the deposit notice, so the bookkeeper can match it",
            referencePlaceholder: "e.g. CA1MRx7Q",
            receivedOn: "Received on",
            chequeNo: "Cheque number",
            note: "Note",
            notePlaceholder: "Seen by staff only",
            sendReceipt: "Email a receipt",
            sendReceiptTo: (email: string) => `To ${email}`,
            thisPayment: "This payment",
            resultPaid: "Paid in full",
            resultPartial: "Still owing",
            charge: (amount: string) => `Charge ${amount}`,
            record: (amount: string) => `Record ${amount}`,
            recording: "Recording…",
            charging: "Charging…",
            amountInvalid: "Enter an amount more than $0.",
            amountTooHigh: (max: string) => `That's more than the ${max} owing.`,
            tenderedShort: "That's less than the amount being paid.",
            dateInvalid: "Use a date like 2026-10-07, and not one in the future.",
            error: "Couldn't record the payment. Nothing was charged; try again.",
            doneTitle: "Payment recorded",
            cardTitle: "Card charge started",
            cardBody: "The invoice updates when the card payment settles, usually within a minute.",
            donePaid: (n: string) => `Invoice ${n} is paid in full.`,
            donePartial: (n: string, left: string) => `Invoice ${n} has ${left} left to pay.`,
            receiptSent: (email: string) => `Receipt sent to ${email}.`,
            giveChange: (amount: string) => `Give ${amount} change.`,
            recordAnother: "Record another payment",
            nothingOwed: "Nothing left to record on this invoice.",
        },
        doc: {
            title: "Documents",
            kinds: { invoice: "Invoice", estimate: "Estimate", receipt: "Receipt" },
            fileName: (business: string, kind: string, n: string) =>
                `${business.replace(/[^A-Za-z0-9]+/g, "-")}-${kind}-${n}.pdf`,
            pages: "1 page",
            print: "Print",
            download: "Download PDF",
            share: "Share",
            email: "Email to client",
            emailedTo: (to: string) => `Sent again to ${to}.`,
            back: "Back",
            attachedTo: "Sent with",
            attachedInvoice: (when: string) => `Invoice email, ${when}`,
            attachedEstimate: (when: string) => `Estimate email, ${when}`,
            attachedReceipt: (when: string) => `Receipt email, ${when}`,
            notSentYet: "Not sent yet",
            noReceipt: "No payment on this invoice yet, so there's no receipt.",
            noEstimate: "This invoice didn't start as an estimate.",
            downloadHint: "Download opens your browser's print dialog; choose Save as PDF.",
        },
        incompleteInvoice: "Pick a client and add at least one line.",
        refundAmountPlaceholder: (remaining: string) => `Up to ${remaining}`,
        refundAmountInvalid: "Enter an amount up to what's left to refund.",
        refundError: "Couldn't refund this payment. Please try again.",
        refund: "Refund",
        refunding: "Refunding…",
        refundTitle: "Refund payment",
        refundConfirm: "Refund this payment? This can't be undone.",
        refundBadge: "Refund",
    },
    printing: {
        kinds: { invoice: "INVOICE", estimate: "ESTIMATE", receipt: "RECEIPT" },
        from: "From",
        billTo: "Bill to",
        preparedFor: "Prepared for",
        receivedFrom: "Received from",
        issued: "Issued",
        due: "Due",
        validUntil: "Valid until",
        paidOn: "Paid",
        invoiceNumber: "Invoice",
        estimateNumber: "Estimate",
        receiptNumber: "Receipt",
        forInvoice: "For invoice",
        item: "Item",
        qty: "Qty",
        price: "Price",
        tax: "Tax",
        amount: "Amount",
        paymentMethod: "Payment method",
        amountPaid: "Amount paid",
        balanceRemaining: "Balance remaining",
        estimateTotal: "Estimate total",
        taxSummary: "Tax summary",
        taxBase: "On",
        howToPay: "How to pay",
        payOnline: (url: string) => `Pay online at ${url}`,
        payInterac: (email: string) =>
            `Interac e-Transfer to ${email}, with the invoice number in the message`,
        acceptOnline: (url: string) => `Read and accept it online at ${url}`,
        acceptBy: (when: string) => `To go ahead, accept before ${when}.`,
        thanks: "Thank you for your business.",
        page: "Page 1 of 1",
        registration: (parts: string[]) => parts.join(" · "),
        gstNo: (n: string) => `GST/HST ${n}`,
        qstNo: (n: string) => `QST ${n}`,
        scanToPay: "Scan to pay",
        paidStamp: "Paid",
        forPet: (pet: string) => `for ${pet}`,
        draftNumber: "Draft",
    },
    pos: {
        addItemFirst: "Add an item before charging.",
        totalError: "Couldn't total this sale. Please try again.",
        chargeStartError: "Couldn't start the charge. Please try again.",
        voidError: "Couldn't void this sale. Please try again.",
        subtitle: "Ring up a sale.",
        quantity: "quantity",
        removeLine: "Remove line",
        searchPlaceholder: "Search catalog…",
        searchEmpty: "No items match your search.",
        emptyCatalog: "No sellable catalog items yet.",
        empty: "No sellable items yet.",
        cart: "Cart",
        clear: "Clear",
        cartEmpty: "Tap a catalog item to add it.",
        cartEmptyStart: "Tap a catalog item to start a sale.",
        unitEach: (money: string) => `${money} each`,
        subtotal: "Subtotal",
        tax: "Tax",
        total: "Total",
        plusTax: " + tax",
        charge: (money: string) => `Charge ${money}`,
        collect: (money: string) => `Collect ${money}`,
        totalling: "Totalling…",
        reviewTotal: "Review total",
        clientLabel: "Client",
        receiptEmail: "Email receipt to",
        receiptPhone: "Text receipt to",
        receiptHint: "Optional. A client's sale also goes to the client's own contact details.",
        receiptEmailInvalid: "Enter a valid email for the receipt",
        payCard: "Take card payment",
        paying: "Charging…",
        payError: "Couldn't take the payment. Please try again.",
        paidTitle: "Paid",
        paidBody: (money: string) => `${money} received. The receipt is on its way.`,
        tapToPayAmount: (amount: string) => `Tap to Pay · ${amount}`,
        saleDetails: (client: string, open: boolean) => `Client: ${client}  ${open ? "−" : "+"}`,
        alsoSell: "Also sell",
        sellGiftCard: "Gift card",
        sellPackage: "Package",
        sellSubscription: "Subscription",
        chooseClient: "Choose a client first",
        readerTitle: "Charge on reader",
        readerCollect: (money: string) => `Tap, insert, or swipe the card to collect ${money}.`,
        readerRequirements:
            "Tap to Pay needs an EAS dev build + a capable device (or a simulated reader) and a Stripe Terminal location id.",
        readerConnecting: "Connecting reader…",
        readerReady: "Reader ready — tap to charge",
        readerCollecting: "Waiting for the card…",
        readerApproved: "Approved ✓",
        readerUnavailable: "Reader unavailable",
        newSale: "New sale",
        voidSale: "Void this sale",
        openOrders: "Open orders",
        walkIn: "Walk-in",
        onlineOrders: "Online orders for pickup",
        pickup: {
            line: (quantity: number, name: string) => `${String(quantity)} × ${name}`,
            toPack: "To pack",
            ready: "Ready",
            pickedUp: "Picked up",
            guest: "Guest",
            placed: (when: string) => `Placed ${when}`,
            readySince: (when: string) => `Ready since ${when}`,
            pickedAt: (when: string) => `Picked up ${when}`,
            items: (n: number) => (n === 1 ? "1 item" : `${String(n)} items`),
            waiting: (days: number) =>
                days === 0
                    ? "Today"
                    : days === 1
                      ? "Waiting 1 day"
                      : `Waiting ${String(days)} days`,
            emptyToPack: "Nothing to pack. New online orders show up here.",
            emptyReady: "Nothing waiting on the shelf.",
            emptyPickedUp: "Nothing picked up yet.",
            error: "Couldn’t update the order. Try again.",
        },
        markReady: "Mark ready",
        markPickedUp: "Picked up",
    },
    earnings: {
        subtitle: "Approve staff earnings, then mark them paid out.",
        filterTab: (filter: string, count: number) =>
            `${filter.charAt(0).toUpperCase()}${filter.slice(1)} (${String(count)})`,
        empty: (filter: string) => `No ${filter === "all" ? "" : `${filter} `}payouts.`,
        approve: "Approve",
        approving: "Approving…",
        markPaid: "Mark paid",
        approveError: "Couldn't approve this payout. Please try again.",
        markPaidError: "Couldn't mark this payout paid. Please try again.",
        staffFallback: "Staff",
        sourceBooking: "Booking",
        sourceSale: "Sale commission",
    },
    entitlements: {
        giftCards: {
            modePreset: "Preset card",
            modeCustom: "Custom amount",
            sellError: "Couldn't sell this gift card. Please try again.",
            issuedCount: (n: number) => `${n} issued`,
            redeem: "Redeem",
            redeemTitle: "Redeem gift card",
            redeeming: "Redeeming…",
            sell: "Sell gift card",
            sellShort: "Sell",
            selling: "Selling…",
            code: "Code",
            codePlaceholder: "ABCD2345EFGH",
            recipient: "Recipient",
            status: "Status",
            balance: "Balance",
            emptyList: "No gift cards issued yet.",
            ofInitial: (initial: string) => `of ${initial}`,
            amountFallback: "gift card",
            purchaser: "Purchaser",
            addClientFirst: "Add a client first.",
            type: "Type",
            giftCard: "Gift card",
            selectGiftCard: "Select a gift card",
            emptyCatalog: "No gift cards in your catalog.",
            amountCad: "Amount (CAD)",
            amountPlaceholder: "100.00",
            redeemAmountPlaceholder: "25.00",
            recipientOptional: "Recipient (optional)",
            recipientPlaceholder: "Name or email",
            selectClient: "Select a client",
            choosePurchaser: "Choose a purchaser",
            chooseGiftCard: "Choose a gift card",
            enterAmount: "Enter a gift card amount",
            enterCode: "Enter a gift card code",
            enterRedeemAmount: "Enter a redemption amount",
            redeemError: "Couldn't redeem this gift card. Please try again.",
        },
    },
    bookings: {
        eventTooltip: (time: string, title: string, subtitle: string) =>
            [time, title, subtitle].filter(Boolean).join(" · "),
        collectDepositError: "Couldn't collect the deposit. Please try again.",
        addonsTitle: "Added to this visit",
        addonsNote: "Added online by the client. They pay for these with the visit.",
        addonRemove: "Remove",
        addonRemoveError: "Couldn't remove this item. Please try again.",
        invoiceVisit: "Create invoice",
        invoiceVisitError: "Couldn't create the invoice. Please try again.",
        visitInvoiced: "This visit has an invoice.",
        seriesSkippedNotice: (created: number, skipped: number) =>
            `Booked ${created}, skipped ${skipped} (already taken or outside hours).`,
        createSeriesError: "Could not create the series. Please try again.",
        bookError: "Could not book — that time may already be taken.",
        viewDay: "Day",
        viewWeek: "Week",
        viewMonth: "Month",
        viewStaff: "Staff",
        viewAgenda: "Agenda",
        today: "Today",
        prev: "Previous",
        viewLabel: "Calendar view",
        next: "Next",
        todayPrefix: "Today · ",
        newBookingButton: "+ New booking",
        newBooking: "New booking",
        moreCount: (n: number) => `+${n} more`,
        noBookings: "No bookings",
        client: "Client",
        selectClient: "Select a client",
        service: "Service",
        selectService: "Select a service",
        staff: "Staff",
        date: "Date",
        time: "Time",
        repeatBooking: "Repeat this booking",
        every: "Every",
        frequency: "Frequency",
        occurrences: "Occurrences",
        booking: "Booking…",
        bookSeries: "Book series",
        book: "Book",
        canceling: "Canceling…",
        cancelBooking: "Cancel booking",
        deposit: "Deposit",
        collecting: "Collecting…",
        collectAmount: (amount: string) => `Collect ${amount}`,
        cancelError: "Couldn't cancel this booking. Please try again.",
        incompleteBooking: "Pick a client, service, and time.",
        freqDaily: "Daily",
        freqWeekly: "Weekly",
        freqMonthly: "Monthly",
        unitDays: "Days",
        unitWeeks: "Weeks",
        unitMonths: "Months",
        repeat: "Repeat",
        oneTime: "One-time",
    },
    forms: {
        fieldTypeText: "Short text",
        fieldTypeLongtext: "Paragraph",
        fieldTypeEmail: "Email",
        fieldTypePhone: "Phone",
        fieldTypeNumber: "Number",
        fieldTypeCurrency: "Amount",
        fieldTypeDate: "Date",
        fieldTypeTime: "Time",
        fieldTypeSelect: "Dropdown",
        fieldTypeMultiselect: "Multi-select",
        fieldTypeCheckbox: "Checkbox",
        fieldTypeAddress: "Address",
        fieldTypeRating: "Rating",
        fieldTypeFile: "File",
        fieldTypeImage: "Image",
        fieldTypeSignature: "Signature",
        ownerAdminOnly: "Only owners and admins can manage forms and contracts.",
        intro: "Build intake forms and contracts, then send them to clients to complete.",
        intakeForms: "Intake forms",
        newForm: "New form",
        sendForm: "Send form",
        sendFormTitle: "Send a form",
        emptyForms: "No forms yet. Create one to send to clients.",
        fieldCount: (n: number) => `${n} field${n === 1 ? "" : "s"}`,
        signatureRequired: " · signature required",
        form: "Form",
        selectForm: "Select a form",
        client: "Client",
        selectClient: "Select a client",
        formName: "Form name",
        formNamePlaceholder: "New client intake",
        addField: "+ Add field",
        requireSignature: "Require a signature",
        createForm: "Create form",
        fieldN: (n: number) => `Field ${n}`,
        remove: "Remove",
        fieldLabelPlaceholder: "Field label",
        fieldType: "Field type",
        optionsPlaceholder: "Options, comma separated",
        required: "Required",
        sendFormError: "Couldn't send the form. Please try again.",
        formNameRequired: "Name is required",
        addFieldError: "Add at least one field",
        saveFormError: "Couldn't save the form. Please try again.",
    },
    contracts: {
        client: "Client",
        selectClient: "Select a client",
        contracts: "Contracts",
        newContract: "New contract",
        sendForSignature: "Send for signature",
        emptyContracts: "No contracts yet. Create one to send for signature.",
        version: (n: number) => `Version ${n}`,
        contract: "Contract",
        selectContract: "Select a contract",
        send: "Send",
        secureLinkNotice:
            "The client signs on a secure link. Status appears here once they respond.",
        name: "Name",
        contractNamePlaceholder: "Service agreement",
        contractText: "Contract text",
        contractTextPlaceholder: "Paste or write the contract the client will sign…",
        createContract: "Create contract",
        sendContractError: "Couldn't send the contract. Please try again.",
        contractNameRequired: "Name is required",
        contractTextRequired: "Contract text is required",
        saveContractError: "Couldn't save the contract. Please try again.",
    },
    clients: {
        sellPackageError: "Couldn't sell this package. Please try again.",
        title: "Clients",
        total: (count: number) => `${count} total`,
        add: "Add client",
        addShort: "Add",
        searchPlaceholder: "Search clients…",
        colName: "Name",
        colPhone: "Phone",
        colStatus: "Status",
        colLifetime: "Lifetime",
        dash: "—",
        empty: "No clients yet.",
        emptySearch: "No clients match your search.",
        manageRestricted:
            "Only owners and admins can manage payment methods, subscriptions, and packages.",
        paymentMethods: "Payment methods",
        noPaymentMethods: "No saved payment methods yet.",
        starting: "Starting…",
        addCard: "Add card",
        addBankWeb: "Add bank (pre-authorized debit)",
        setDefaultError: "Couldn't set the default. Please try again.",
        removeMethodTitle: "Remove payment method",
        removeMethodConfirm: "Remove this payment method?",
        removeMethodError: "Couldn't remove this method. Please try again.",
        defaultTag: "Default",
        makeDefault: "Make default",
        remove: "Remove",
        cardNoun: "card",
        bankAccountNoun: "bank account",
        saveMethod: (noun: string) => `Save ${noun}`,
        subscriptions: "Subscriptions",
        startSubscriptionLink: "+ Start subscription",
        noSubscriptions: "No subscriptions yet.",
        subscriptionFallback: "Subscription",
        nextCharge: (date: string) => `Next charge ${date}`,
        cancelSubscriptionTitle: "Cancel subscription",
        cancelSubscriptionConfirm: "Cancel this subscription?",
        cancelSubscriptionError: "Couldn't cancel this subscription. Please try again.",
        keep: "Keep",
        canceling: "Canceling…",
        planLabel: "Plan",
        selectPlan: "Select a subscription plan",
        addSubscriptionItemFirst: "Add a subscription item in your catalog first.",
        startSubscription: "Start subscription",
        packages: "Packages",
        sellPackageLink: "+ Sell package",
        noPackages: "No packages yet.",
        packageFallback: "Package",
        packageAmountFallback: "package",
        consumeSessionError: "Couldn't consume a session. Please try again.",
        sessionsLeft: (remaining: number, total: number) =>
            `${remaining} of ${total} sessions left`,
        sessionsLeftShort: (remaining: number, total: number) => `${remaining} of ${total} left`,
        consumeSession: "Consume session",
        consumeShort: "Consume",
        packageLabel: "Package",
        selectPackage: "Select a package",
        addPackageItemFirst: "Add a package item in your catalog first.",
        sellPackage: "Sell package",
        selling: "Selling…",
        addClientTitle: "Add client",
        nameLabel: "Name",
        emailLabel: "Email",
        phoneLabel: "Phone",
        adding: "Adding…",
        addClient: "Add client",
        nameRequired: "Name is required",
        addError: "Could not add client",
        choosePackage: "Choose a package",
        choosePlan: "Choose a subscription plan",
        startSubscriptionError: "Couldn't start the subscription. Please try again.",
    },
    messaging: {
        channelSms: "Text",
        channelEmail: "Email",
        channelChat: "Chat",
        title: "Inbox",
        subtitle: "Message clients and send broadcasts.",
        broadcast: "Broadcast",
        newMessage: "New message",
        newShort: "New",
        noConversations: "No conversations yet.",
        selectConversation: "Select a conversation to read and reply.",
        clientFallback: "Client",
        noMessages: "No messages yet.",
        replyBy: (channel: string) => `Reply by ${channel}…`,
        send: "Send",
        sending: "Sending…",
        newMessageTitle: "New message",
        clientLabel: "Client",
        selectClient: "Select a client",
        addClientFirst: "Add a client first.",
        channelLabel: "Channel",
        messageLabel: "Message",
        messagePlaceholder: "Write a message…",
        sendMessage: "Send message",
        broadcastScheduled: "Broadcast scheduled",
        broadcastSent: "Broadcast sent",
        broadcastRecipients: (name: string, count: number) =>
            `${name} · ${count} recipient${count === 1 ? "" : "s"}.`,
        broadcastRecipientsShort: (name: string, count: number) =>
            `${name} · ${count} recipient${count === 1 ? "" : "s"}`,
        newBroadcastTitle: "New broadcast",
        nameLabel: "Name",
        namePlaceholder: "Spring promo",
        announcementPlaceholder: "Write your announcement…",
        audienceTagsLabel: "Audience tags",
        audienceTagsOptional: "Audience tags (optional)",
        optional: "(optional)",
        tagsPlaceholderWeb: "vip, regulars — leave blank for everyone",
        tagsPlaceholderShort: "vip, regulars — blank = everyone",
        scheduleLabel: "Schedule",
        sendBroadcast: "Send broadcast",
        writeMessage: "Write a message",
        sendError: "Couldn't send your message. Please try again.",
        nameBroadcast: "Name your broadcast",
        broadcastError: "Couldn't send the broadcast. Please try again.",
    },
    reviews: {
        postReplyError: "Couldn't post your reply. Please try again.",
        hideError: "Couldn't hide this review. Please try again.",
        publishError: "Couldn't publish this review. Please try again.",
        sendRequestError: "Couldn't send the review request. Please try again.",
        subtitle: "Reply to feedback and choose what shows publicly.",
        requestReview: "Request review",
        noReviews: "No reviews yet.",
        loadingRating: "Loading rating…",
        ratingLoadError: "Couldn't load your rating.",
        noPublishedReviews: "No published reviews yet.",
        publishedCount: (count: number) => `${count} published review${count === 1 ? "" : "s"}`,
        awaitingCount: (count: number) =>
            `${count} request${count === 1 ? "" : "s"} waiting for a reply`,
        clientFallback: "Client",
        yourReply: "Your reply",
        replyPlaceholder: "Write a public reply…",
        postReply: "Post reply",
        editReply: "Edit reply",
        reply: "Reply",
        publish: "Publish",
        hide: "Hide",
        requestTitle: "Request a review",
        clientLabel: "Client",
        selectClient: "Select a client",
        addClientFirst: "Add a client first.",
        sending: "Sending…",
        sendRequest: "Send request",
    },
    business: {
        setupSteps: {
            service: {
                label: "Add a service",
                hint: "What clients book, with its length and price",
            },
            hours: { label: "Set your hours", hint: "When you take bookings each week" },
            client: { label: "Add your first client", hint: "Or import the clients you have" },
            team: { label: "Invite your team", hint: "Staff see their own schedule and clients" },
            stripe: { label: "Connect Stripe", hint: "Take cards and deposits. About 5 minutes." },
            page: { label: "Share your booking page" },
        },
        subtitle: "Your business profile and tax registration.",
        language: "Language",
        nameLabel: "Business name",
        namePlaceholder: "Birch Bark Pet Care",
        timezoneLabel: "Time zone",
        timezonePlaceholder: "America/Toronto",
        billingEmailLabel: "Billing email",
        billingEmailPlaceholder: "you@example.com",
        gstLabel: "GST/HST number",
        gstPlaceholder: "123456789RT0001",
        qstLabel: "QST number",
        qstPlaceholder: "1234567890TQ0001",
        nameRequired: "Business name is required",
        saveError: "Could not save account settings",
        brandTitle: "Brand",
        brandSubtitle: "Shown to your clients on booking, pay, and other links.",
        primaryLabel: "Primary colour",
        primaryPlaceholder: "#3F5E80",
        taglineLabel: "Tagline",
        taglinePlaceholder: "Calm, careful grooming on the island.",
        onboarding: {
            provinceAB: "Alberta",
            provinceBC: "British Columbia",
            provinceMB: "Manitoba",
            provinceNB: "New Brunswick",
            provinceNL: "Newfoundland and Labrador",
            provinceNS: "Nova Scotia",
            provinceNT: "Northwest Territories",
            provinceNU: "Nunavut",
            provinceON: "Ontario",
            provincePE: "Prince Edward Island",
            provinceQC: "Quebec",
            provinceSK: "Saskatchewan",
            provinceYT: "Yukon",
            settingUp: "Setting up your workspace…",
            title: "Create your business",
            subtitleWeb:
                "Tell us about your practice — we’ll set up your bookings, invoices, and the right tax rates for your province.",
            subtitleMobile:
                "We’ll set up your bookings, invoices, and the right tax rates for your province.",
            businessName: "Business name",
            businessNamePlaceholder: "Birch Bark Pet Care",
            webAddress: "Web address",
            slugPrefix: "clientbridge.ca/",
            slugPlaceholder: "birch-bark",
            province: "Province",
            creating: "Creating…",
            createBusiness: "Create business",
            notYou: "Not you?",
            signOut: "Sign out",
            notYouSignOut: "Not you? Sign out",
            nameRequired: "Business name is required",
            slugRequired: "A web address is required",
            createError: "Couldn’t create your business — that web address may be taken.",
        },
    },
    hours: {
        title: "Working hours",
        subtitle:
            "Set each team member’s weekly working hours. Bookings are held to these windows.",
        noStaff: "No team members yet.",
        teamMember: "Team member",
        from: "Opens",
        to: "to",
        closed: "Closed",
        saveHours: "Save hours",
        startHint: "09:00",
        endHint: "17:00",
        timeFormatError: "Times must be in HH:MM format",
        timeOrderError: "Each open day needs a start time before its end time",
        saveError: "Couldn't save hours. Please try again.",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        sunday: "Sunday",
    },
    staff: {
        inviteMissingCode: "This invite link is missing its code.",
        passwordTooShort: "Choose a password of at least 8 characters.",
        acceptInviteError: "Couldn’t accept this invite — it may be invalid or expired.",
        subtitle: "Invite colleagues and manage who can access your business.",
        noMembers: "No team members yet.",
        members: "Members",
        youBadge: "You",
        youSuffix: " (You)",
        pending: "Pending invites",
        invitedBadge: (role: string) => `${role} · invited`,
        cannotInvite: "Only owners and admins can invite teammates.",
        inviteHeading: "Invite a teammate",
        email: "Email",
        emailPlaceholder: "teammate@example.com",
        role: "Role",
        inviting: "Inviting…",
        sendInvite: "Send invite",
        inviteSentWeb: (email: string) =>
            `Invite sent to ${email}. Share this link so they can join:`,
        inviteSentMobile: (email: string) => `Invite sent to ${email}. Share this link:`,
        copied: "Copied",
        copy: "Copy",
        shareLink: "Share link",
        emailRequired: "An email is required",
        inviteError: "Couldn’t send that invite — check the email and try again.",
        roleOwner: "Owner",
        roleStaff: "Staff",
        roleAdmin: "Admin",
        roleContractor: "Contractor",
        payHeading: "Pay",
        isPayee: "Pay this member through Staff pay",
        rateType: "Paid for services by",
        ratePercent: "Percent of the service price",
        rateFixed: "Fixed amount per booking",
        rateHourly: "Hourly rate",
        rateLabel: (type: string) =>
            type === "percent" ? "Rate (%)" : type === "hourly" ? "Rate ($ per hour)" : "Rate ($)",
        retailRate: "Commission on products sold (%)",
        rateInvalid: "Enter a rate of 0 or more (a percentage can't be over 100)",
        retailInvalid: "Enter a commission between 0 and 100",
        payError: "Couldn't save this member's pay",
        notPaid: "Not paid through Staff pay",
        payPercent: (rate: number) => `${String(rate)}% of services`,
        payFixed: (money: string) => `$${money} per booking`,
        payHourly: (money: string) => `$${money} an hour`,
        payWithRetail: (service: string, retail: number) =>
            `${service} · ${String(retail)}% on products`,
    },
    catalog: {
        title: "Catalog",
        summary: (items: number, low: number) =>
            low > 0
                ? `${String(items)} items · ${String(low)} need restocking`
                : `${String(items)} items`,
        views: { catalog: "Catalog", products: "Products", inventory: "Inventory" },
        viewsLabel: "Catalog views",
        addItem: "Add item",
        addShort: "Add",
        searchPlaceholder: "Search name, category or SKU",
        filterAll: "All",
        filterServices: "Services",
        filterProducts: "Products",
        filterPlans: "Plans",
        filterLowStock: "Low stock",
        filterArchived: "Archived",
        filterNotOnline: "Not in shop",
        filterCount: (label: string, n: number) => `${label} ${String(n)}`,
        noMatch: "No items match that search.",
        filterEmpty: "Nothing here right now.",
        countIn: (n: number) => (n === 1 ? "1 item" : `${String(n)} items`),
        groups: {
            service: "Services",
            class: "Classes",
            product: "Products",
            package: "Packages",
            subscription: "Memberships",
            gift: "Gift cards",
        } as Record<string, string>,
        online: "Online",
        inShop: "In shop",
        notOnline: "Desk only",
        archived: "Archived",
        colItem: "Item",
        colType: "Type",
        colPrice: "Price",
        colOnline: "Online",
        loadingCatalog: "Loading your catalog",
        loadErrorCatalog: "Couldn’t load your catalog",
        emptyCatalogTitle: "Nothing in your catalog yet",
        emptyCatalogBody:
            "Add the services you offer and the products you sell. Booking, Sales and the shop all read from here.",
        loadingProducts: "Loading products",
        loadErrorProducts: "Couldn’t load your products",
        emptyProductsTitle: "No products yet",
        emptyProductsBody:
            "Add what you sell at the desk or in the online shop, with a photo, price and stock count.",
        loadingStock: "Loading stock levels",
        loadErrorStock: "Couldn’t load stock levels",
        emptyStockTitle: "No products tracked yet",
        emptyStockBody:
            "Turn on Track stock in a product’s editor and its count, low-stock warning and history show here.",
        emptyDeliveryTitle: "No products to receive",
        emptyDeliveryBody: "Add a product and turn on Track stock, then count deliveries in here.",
        kindService: "Service",
        kindProduct: "Product",
        kindClass: "Class",
        kindPackage: "Package",
        kindSubscription: "Membership",
        kindGift: "Gift card",
        kindHints: {
            service: "Booked by time, one client at a time",
            class: "Booked by time, several clients at once",
            product: "Sold at the desk or in your shop",
            package: "Prepaid visits, used over time",
            subscription: "Billed every week, month or year",
            gift: "Any amount, spent on anything",
        } as Record<string, string>,
        whatAdding: "What are you adding?",
        whatAddingHint: "You can’t change the type later, so pick the closest fit.",
        next: "Next",
        cancel: "Cancel",
        minutes: (n: number) => `${String(n)} min`,
        plusBuffer: (n: number) => ` · ${String(n)} min buffer`,
        classSize: (n: number) => `up to ${String(n)}`,
        visits: (n: number) => (n === 1 ? "1 visit" : `${String(n)} visits`),
        validDays: (days: number | null) =>
            days === null
                ? "no expiry"
                : days % 365 === 0
                  ? `valid ${String((days / 365) * 12)} months`
                  : `valid ${String(days)} days`,
        every: (interval: number, freq: string) =>
            interval === 1 ? `every ${freq}` : `every ${String(interval)} ${freq}s`,
        perPeriod: (money: string, freq: string) => `${money} / ${freq}`,
        anyAmount: "Any amount",
        depositMeta: (label: string) => `${label} deposit`,
        skuLine: (sku: string) => `SKU ${sku}`,
        untracked: "Stock not tracked",
        newItem: (kind: string) => `New ${kind.toLowerCase()}`,
        save: "Save",
        saving: "Saving…",
        add: "Add to catalog",
        archive: "Archive",
        restore: "Restore",
        archivedNote:
            "Archived items are hidden from Sales, booking and the shop. Past sales keep them.",
        sectionBasics: "Basics",
        sectionTime: "Price and time",
        sectionBooking: "Online booking",
        sectionDeposit: "Deposit",
        sectionPrice: "Price",
        sectionTax: "Sales tax",
        sectionStock: "Stock",
        sectionShop: "Selling",
        sectionImage: "Photo",
        sectionPlan: "What it includes",
        name: "Name",
        namePlaceholderService: "e.g. Full Groom: Small Dog",
        namePlaceholderProduct: "e.g. Oatmeal Shampoo (500 ml)",
        description: "Description",
        descriptionHint: "Clients see this on your booking page and in the shop.",
        category: "Category",
        price: "Price",
        durationLabel: "Duration (min)",
        bufferBefore: "Setup before (min)",
        bufferAfter: "Clean-up after (min)",
        capacity: "Class size",
        capacityHint: "How many clients can book one class.",
        onlineBookable: "Clients can book this online",
        onlineBookableHint: "Shows on your booking page with the times you’re open.",
        depositNone: "None",
        depositFixed: "Fixed",
        depositPercent: "Percent",
        depositAmount: "Deposit amount",
        depositPercentLabel: "Deposit percent",
        depositSummary: (deposit: string, rest: string) =>
            `Clients pay ${deposit} when they book. The other ${rest} is due at the visit.`,
        depositNoneSummary:
            "Clients pay at the visit. Without a deposit, no-shows cost you the slot.",
        timelineCaption: (total: number, before: number, main: number, after: number) =>
            before + after === 0
                ? `Blocks ${String(total)} min on the calendar.`
                : `Blocks ${String(total)} min: ${[
                      before > 0 ? `${String(before)} min setup` : "",
                      `${String(main)} min with the client`,
                      after > 0 ? `${String(after)} min clean-up` : "",
                  ]
                      .filter(Boolean)
                      .join(", ")}. No one else can book the buffers.`,
        mainSegment: (name: string, minutes: number) => `${name} · ${String(minutes)} min`,
        taxClass: "Tax",
        taxAll: "All sales taxes",
        taxJoin: (codes: string[]) => codes.join(" and "),
        taxOnly: (codes: string) => `${codes} only`,
        taxFederalOnly: "GST or HST only",
        taxExempt: "No tax",
        taxNotRegistered: "You don’t collect sales tax yet, so clients pay the price as listed.",
        taxHintService:
            "Which taxes apply to a service depends on your province. Confirm with your accountant.",
        taxHintProduct:
            "Retail usually carries every sales tax in your province. Confirm with your accountant.",
        taxPreview: (rates: string, money: string) => `${rates}: a client pays ${money}`,
        productsSummary: (n: number, value: string) =>
            `${String(n)} products · ${value} on the shelf at cost`,
        addProduct: "Add product",
        photo: "Add photo",
        changePhoto: "Change photo",
        photoHint: "Square photos look best. JPG or PNG, up to 10 MB. Drop a file here or click.",
        photoAfterSave: "Save the product first, then add its photo.",
        photoOnWeb:
            "Taking or choosing a photo on the phone comes with the next app update. Add it from the web for now.",
        photoUploaded: "Photo updated.",
        sku: "SKU",
        skuHint: "Optional. Your own code or the barcode number.",
        cost: "Your cost",
        costHint: "What you pay the supplier. Never shown to clients.",
        margin: "Margin",
        marginSummary: (money: string, pct: number) => `${money} a sale · ${String(pct)}%`,
        marginUnknown: "Add your cost to see the margin",
        marginLow: "Below 30%: check the price",
        trackStock: "Track stock",
        trackStockHint: "Counts go down as you sell and back up on refunds and restocks.",
        stockOnHand: "On hand now",
        lowAt: "Warn at",
        lowAtHint: "We flag it as low at or below this count.",
        sellOnline: "Sell in the online shop",
        sellOnlineHint: "Clients can buy it for pickup.",
        colProduct: "Product",
        colCost: "Cost",
        colMargin: "Margin",
        colStock: "Stock",
        colSold: "Sold 30d",
        colShop: "Shop",
        marginPct: (pct: number) => `${String(pct)}%`,
        sold30: (n: number) => `${String(n)} sold in 30 days`,
        sortBy: "Sort by",
        sortName: "Name",
        sortMargin: "Margin",
        sortStock: "Stock",
        stockOut: "Out of stock",
        stockLow: (n: number) => `Low: ${String(n)} left`,
        stockIn: (n: number) => `${String(n)} in stock`,
        inventoryTitle: "Inventory",
        inventorySubtitle: "Products you track stock for.",
        statTracked: "Tracked products",
        statLow: "Low",
        statOut: "Out of stock",
        statValue: "Stock at cost",
        statRetail: (money: string) => `${money} at retail`,
        needsRestock: "Needs restocking",
        needsRestockHint: "Low or out, most urgent first.",
        allTracked: "All tracked products",
        allGood: "Everything is above its low-stock line.",
        restock: "Restock",
        receive: "Receive stock",
        suggested: (n: number) => `Suggest ordering ${String(n)}`,
        daysLeft: (n: number) =>
            n <= 0 ? "Sold out" : n === 1 ? "About a day left" : `About ${String(n)} days left`,
        restockTitle: (name: string) => `Restock ${name}`,
        restockQuantity: "Units received",
        restockQuantityHint: "Use a negative number to correct a miscount.",
        restockNote: "Note",
        restockNotePlaceholder: "Delivery, supplier or reason",
        restockAfter: (n: number) => `${String(n)} on hand after this`,
        restockSave: "Add to stock",
        restocking: "Saving…",
        restockDone: (n: number, name: string) =>
            n < 0 ? `Corrected ${name} by ${String(n)}.` : `Added ${String(n)} to ${name}.`,
        restockInvalid: "Enter a whole number other than zero",
        restockError: "Could not update stock",
        openingStockNote: "Opening count",
        moveKinds: {
            sale: "Sold at the desk",
            online: "Sold online",
            invoice: "Sold on an invoice",
            refund: "Refunded",
            restock: "Restocked",
            correction: "Corrected",
        } as Record<string, string>,
        moveQty: (n: number) => (n > 0 ? `+${String(n)}` : `−${String(Math.abs(n))}`),
        moveLabel: (name: string, qty: string) => `${name} ${qty}`,
        by: (name: string) => `by ${name}`,
        recentMoves: "Recent stock changes",
        noMoves: "Stock changes show here as you sell and restock.",
        backToInventory: "Inventory",
        receiveTitle: "Receive a delivery",
        receiveSubtitle: "Count everything in one go. Each product’s stock goes up when you save.",
        supplier: "Supplier",
        supplierPlaceholder: "e.g. Coastal Pet Supply",
        reference: "Packing slip or PO",
        referencePlaceholder: "e.g. INV-30417",
        addSearch: "Search products to add",
        deliveryEmpty: "Add the products in this delivery.",
        colOnHand: "On hand",
        colReceived: "Received",
        colAfter: "After",
        colUnitCost: "Unit cost",
        colLineCost: "Cost",
        onHandShort: (n: number) => `${String(n)} on hand`,
        onHandAfter: (from: number, to: number) => `On hand ${String(from)} → ${String(to)}`,
        unitCostHint: "Changed costs update the product.",
        deliveryTotal: (units: number, money: string) => `${String(units)} units · ${money}`,
        removeLine: (name: string) => `Remove ${name}`,
        receivedFor: (name: string) => `Received ${name}`,
        unitCostFor: (name: string) => `Unit cost for ${name}`,
        receiveSave: (n: number) =>
            n === 1 ? "Receive 1 product" : `Receive ${String(n)} products`,
        received: (n: number) =>
            n === 1 ? "Stock updated for 1 product." : `Stock updated for ${String(n)} products.`,
        receiveError: "Couldn’t save this delivery. Please try again.",
        receiveInvalid: "Enter a whole number for each product, or remove it",
        lowAfter: "Still low",
        covers: "Each visit covers",
        coversHint: "Booking one of these will use a visit instead of charging.",
        chooseService: "Choose a service",
        visitsLabel: "Visits",
        validForDays: "Valid for (days)",
        noExpiryHint: "Leave blank for no expiry",
        billsEvery: "Bills every",
        includes: "Visits each period",
        includesHint: "Visits reset at each renewal and don’t roll over.",
        memberPerk: "Member retail discount (%)",
        memberPerkHint: "Taken off products at checkout.",
        giftAmounts: "Suggested amounts",
        giftAmountsHint: "Staff and clients can still enter any amount.",
        giftNote: "Gift cards don’t expire and can be spent on anything.",
        perVisit: (money: string) => `${money} a visit`,
        saves: (money: string, n: number, name: string) =>
            `Saves ${money} against ${String(n)} × ${name}`,
        noSaving: "No saving against paying each visit",
        perYear: (money: string) => `${money} a year`,
        planSummaryPackage: (n: number, name: string) => `${String(n)} × ${name}`,
        planSummaryIncomplete: "Choose the service and how many visits it includes",
        planSummaryMembership: (money: string, freq: string) => `${money} every ${freq}`,
        sellsAt: "Sells from Sales, with its own checkout.",
        freqLabel: { day: "day", week: "week", month: "month", year: "year" } as Record<
            string,
            string
        >,
        freqWeek: "Every week",
        freqMonth: "Every month",
        freqYear: "Every year",
        nameRequired: "Give it a name",
        priceInvalid: "Enter a price like 45 or 45.00",
        durationRequired: "Set how long it takes, in minutes",
        depositRequired: "Enter the deposit amount",
        depositPercentMax: "A percentage deposit can’t be over 100",
        sessionsRequired: "Set how many visits the package includes",
        coversRequired: "Choose which service a visit covers",
        intervalRequired: "Set how often it bills",
        perkInvalid: "Enter a discount between 0 and 100",
        stockInvalid: "Stock on hand must be a whole number",
        addError: "Couldn’t add the item. Please try again.",
        saveError: "Couldn’t save the item. Please try again.",
    },
    taxes: {
        title: "Taxes",
        subtitle: "Sales tax applied to your invoices, based on your province.",
        empty: "No tax rates set for your province yet.",
        colTax: "Tax",
        colProvince: "Province",
        footnote:
            "Rates are seeded per province; small-supplier and registration settings come with the payments slice.",
    },
    payments: {
        setupStartError: "Couldn't start payment setup. Please try again.",
        bankAccountNoun: "Bank account",
        cardNoun: "Card",
        interacNoun: "Interac e-Transfer",
        savedCardLabel: (noun: string, last4: string) => `${noun} ···· ${last4}`,
    },
    gettingPaid: {
        reqExternalAccount: "Bank account for payouts",
        reqBusinessWebsite: "Business website",
        reqBusinessCategory: "Business category",
        reqProductDescription: "What you sell",
        reqIdNumber: "ID number (SIN)",
        reqPhotoId: "Photo ID",
        reqProofOfAddress: "Proof of address",
        reqHomeAddress: "Home address",
        reqBusinessNumber: "Business number",
        reqTosAcceptance: "Accept Stripe's terms",
        reqDateOfBirth: "Date of birth",
        headlineNotConnected: "Connect Stripe to take card payments and get paid out.",
        headlineInProgress: "Onboarding in progress — finish your Stripe setup.",
        headlinePending:
            "Stripe is reviewing your details. No action needed — this updates automatically.",
        headlineRestricted: "Stripe needs a bit more to keep your payments active:",
        headlineEnabled: "Payments enabled — you can take card payments.",
        headlineDisabled:
            "Your Stripe account can't accept payments right now. Please contact support.",
        finishVerification: "Finish verification",
        continueSetup: "Continue setup",
        connectStripe: "Connect Stripe",
        onboardingStartError: "Couldn't start Stripe onboarding. Please try again.",
        subtitle: "Take card payments through Stripe and get paid out to your bank.",
        loadError: "We couldn’t load your payment status. Please try again.",
        tryAgain: "Try again",
        opening: "Opening…",
        payoutsActive: "Connected to Stripe. Payouts are active.",
        payoutsPending: "Connected to Stripe. Payouts start once your bank details are verified.",
    },
    today: {
        title: "Today",
        goodMorning: "Good morning",
        goodAfternoon: "Good afternoon",
        goodEvening: "Good evening",
        greetingNamed: (part: string, name: string) => `${part}, ${name}`,
        newBooking: "New booking",
        newSale: "New sale",
        booked: "Booked today",
        bookedHint: (done: number, left: number) => `${String(done)} done, ${String(left)} to go`,
        expected: "Still to come",
        expectedHint: "left to take today, after deposits",
        collected: "Collected today",
        collectedHint: (n: number) =>
            n === 1 ? "1 payment, after refunds" : `${String(n)} payments, after refunds`,
        awaiting: "Awaiting payment",
        awaitingHint: (n: number) => (n === 1 ? "1 open invoice" : `${String(n)} open invoices`),
        setAside: "GST/HST set aside",
        filing: (due: string, days: number) =>
            days === 0 ? `Return due today, ${due}` : `Return due ${due}, in ${String(days)} days`,
        filingShort: (due: string) => `Due ${due}`,
        notRegistered: "Not registered for GST/HST, so nothing is set aside.",
        schedule: "Today’s schedule",
        openSchedule: "Open schedule",
        needsYou: "Needs you",
        allClear: "Nothing needs you right now.",
        team: "Team today",
        teamOff: "Off today",
        teamCount: (n: number) => (n === 1 ? "1 booking" : `${String(n)} bookings`),
        quietTitle: "A quiet day",
        quietBody:
            "Nothing is booked and nothing is waiting on you. Share your booking page or add a booking.",
        shareBookingPage: "Copy booking link",
        shareLink: "Share booking link",
        linkCopied: "Link copied",
        stateNow: "In progress",
        stateNext: "Up next",
        stateNoShow: "No-show",
        stateDone: "Done",
        depositDue: "Deposit due",
        classBooked: (n: number, cap: number) => `${String(n)} of ${String(cap)} booked`,
        nowLine: (time: string) => `Now ${time}`,
        checkIn: "Check in",
        checkout: "Checkout",
        checkedIn: "Checked in",
        inMinutes: (m: number) =>
            m < 60
                ? `in ${String(m)} min`
                : `in ${String(Math.floor(m / 60))} h${m % 60 ? ` ${String(m % 60)} min` : ""}`,
        endsAt: (time: string) => `until ${time}`,
        withStaff: (name: string) => `with ${name}`,
        upNext: "Up next",
        restOfDay: "Later today",
        hoursValue: (from: string, to: string) => `${from} to ${to}`,
        loading: "Loading today",
        loadError: "Couldn’t load today",
        loadErrorBody:
            "Check your connection. Your schedule on this device is still here once it loads.",
        numbersError: "Couldn’t load your numbers",
        numbersErrorBody:
            "Money figures come from the server. Your bookings and clients are still here.",
        sent: "Sent",
        actionError: "That didn’t go through. Try again.",
        attention: {
            depositTitle: "Deposit not paid",
            depositDetail: (client: string, amount: string, time: string) =>
                `${client}, ${amount} for ${time} today`,
            depositAction: "View",
            overdueTitle: (n: number) => `Invoice #${String(n)} overdue`,
            overdueDetail: (client: string, amount: string, days: number) =>
                days <= 0
                    ? `${client}, ${amount}, due today`
                    : days === 1
                      ? `${client}, ${amount}, 1 day late`
                      : `${client}, ${amount}, ${String(days)} days late`,
            overdueAction: "Remind",
            unreadTitle: (n: number) =>
                n === 1 ? "1 unread message" : `${String(n)} unread messages`,
            unreadDetail: (names: string[]) => `From ${names.join(" and ")}`,
            unreadAction: "Open",
            reviewTitle: (stars: number) => `${String(stars)}-star review to answer`,
            reviewAction: "Reply",
            stockTitle: (item: string) => `${item} is low`,
            stockDetail: (left: number, at: number) =>
                `${String(left)} left, you reorder at ${String(at)}`,
            stockManyTitle: (n: number) => `${String(n)} products running low`,
            stockManyDetail: (a: string, b: string, more: number) =>
                more > 0 ? `${a}, ${b} and ${String(more)} more` : `${a} and ${b}`,
            stockAction: "Restock",
            filingTitle: "GST/HST return to file",
            filingDetail: (amount: string, due: string) => `${amount} to file by ${due}`,
            filingAction: "Prepare",
            earningsTitle: "Staff earnings to approve",
            earningsDetail: (n: number, amount: string) =>
                n === 1 ? `1 earning, ${amount}` : `${String(n)} earnings, ${amount}`,
            earningsAction: "Review",
            draftTitle: "Draft invoice",
            draftDetail: (client: string, amount: string) => `${amount} for ${client}`,
            draftAction: "Review",
        },
        staff: {
            subtitle: (n: number) =>
                n === 0
                    ? "No bookings for you today."
                    : n === 1
                      ? "You have 1 booking today."
                      : `You have ${String(n)} bookings today.`,
            nextClient: "Your next client",
            service: "Service",
            time: "Time",
            client: "Client",
            yourDay: "Your day",
            hours: "Your hours",
            earnings: "Earned, not paid yet",
            earningsHint: "Paid out when your owner runs staff pay",
            lastVisit: (when: string) => `Last visit ${when}`,
            free: (from: string, to: string) => `Free from ${from} to ${to}`,
            dayEnds: (time: string) => `Your day ends at ${time}`,
            message: "Message",
            noNext: "You’re done for today.",
            noNextBody: "New bookings for you show up here as soon as they are made.",
            tomorrow: "Tomorrow",
            messagesForYou: "Messages from your clients",
            nothingElse: "Nothing else on your plate.",
        },
    },
    reports: {
        subtitle: "Income, GST/HST, and T4A — export for your bookkeeper or the CRA.",
        loadError: "Couldn’t load your reports.",
        rangeFrom: "From",
        rangeTo: "To",
        t4aYear: "T4A year",
        incomeTitle: "Income",
        bankDeposits: "Bank deposits",
        bankDepositsSubtitle: "Stripe payouts to your bank account",
        noBankDeposits: "No bank deposits yet.",
        remitTitle: "Filed returns",
        remitAction: (start: string, end: string) => `Record remittance for ${start} to ${end}`,
        remitting: "Recording…",
        remitError: "Couldn't record the remittance. Please try again.",
        remitRow: (start: string, end: string) => `${start} to ${end}`,
        remitNone: "No returns filed yet.",
        incomeSubtitle: "Payments received, net of refunds",
        gross: "Gross",
        refunds: "Refunds",
        net: "Net",
        gstTitle: "GST/HST",
        gstSubtitle:
            "Federal GST/HST on issued invoices — remit to the CRA (PST/QST file separately)",
        gstSubtitleMobile: "Federal GST/HST on issued invoices",
        taxCollected: "GST/HST collected",
        pstCollected: "PST collected",
        qstCollected: "QST collected",
        taxableSales: "Taxable sales",
        gstNumberLabel: "GST/HST number",
        notRegistered: "Not registered",
        t4aTitle: (year: number) => `T4A — ${year}`,
        t4aSubtitle: "Amounts paid to staff payees for the calendar year",
        t4aSubtitleMobile: "Amounts paid to staff payees",
        noPayeeAmounts: (year: number) => `No payee amounts for ${year}.`,
        colPayee: "Payee",
        colTotal: "Total",
        downloadCsv: "Download CSV",
        downloading: "Downloading…",
        csv: "CSV",
        loadingReports: "Loading reports…",
        exportError: "Couldn't export the CSV. Please try again.",
        salesByItemTitle: "Sales by item",
        salesByItemSubtitle: "Services, classes and products sold, before tax",
        noItemSales: "No item sales in this period.",
        colItem: "Item",
        colQty: "Qty",
        colSales: "Sales",
        colTax: "Tax",
        colRefunded: "Refunded",
        qty: (n: number) => (Number.isInteger(n) ? String(n) : n.toFixed(2)),
    },
    auth: {
        invalidCredentials: "Invalid email or password",
        createAccountError: "Could not create that account — try another email",
        heroHeadlineLine1: "The bridge between you",
        heroHeadlineLine2: "and your clients.",
        heroSubtitle:
            "Bookings, invoices, payments, and messaging — synced to every device, online or off. Built for service pros.",
        heroFeatures: ["Scheduling", "Invoicing", "Payments", "GST/HST"],
        signInTitle: "Sign in",
        signUpTitle: "Create your account",
        signInSubtitle: "Welcome back.",
        signUpSubtitle: "Start running your practice in minutes.",
        name: "Name",
        namePlaceholder: "Hannah Bauer",
        email: "Email",
        emailPlaceholder: "you@example.com",
        password: "Password",
        passwordPlaceholder: "••••••••",
        signingIn: "Signing in…",
        creatingAccount: "Creating account…",
        signIn: "Sign in",
        createAccount: "Create account",
        or: "or",
        continueWithGoogle: "Continue with Google",
        newToApp: "New to Clientbridge?",
        haveAccount: "Already have an account?",
        createAnAccount: "Create an account",
        inviteTitle: "Accept your invite",
        inviteSubtitle: "Set a password to join your team and start collaborating.",
        inviteMissingCode:
            "This invite link is missing its code. Please use the link from your email.",
        inviteName: "Your name",
        joining: "Joining…",
        joinTeam: "Join team",
        googleNotConfigured: "Google sign-in isn’t configured yet — use email & password.",
    },
    publicPay: {
        notFoundTitle: "Invoice not found",
        notFoundBody:
            "This payment link is invalid or has expired. Please check with the business that sent it to you.",
        cardNotConfigured: "Card payments aren't configured. Please use Interac e-Transfer.",
        requesting: (businessName: string) => `${businessName} sent you an invoice`,
        invoice: "Invoice",
        invoiceNumber: (n: number) => `Invoice #${n}`,
        billedTo: "Billed to",
        issued: "Issued",
        due: "Due",
        dueOn: (when: string) => `Due ${when}`,
        balanceDue: "Balance due",
        total: "Total",
        subtotal: "Subtotal",
        chooseHowToPay: "How would you like to pay?",
        interacLabel: "Interac e-Transfer",
        interacBadge: "From your bank, no fee",
        cardLabel: "Credit or debit card",
        cardBadge: "Visa, Mastercard, Amex",
        payByInterac: "Get my reference code",
        payByCard: "Pay by card",
        interacHeading: "Send your Interac e-Transfer",
        interacSendPrefix: "Send an Interac e-Transfer of",
        interacTo: "to",
        interacAndPut: "and put",
        interacInMessage: "in the message.",
        interacNoEmail: "The business will share their e-Transfer email with you. Send",
        interacConfirmNote:
            "Your payment will be marked as received once the business confirms the transfer.",
        paidTitle: "This invoice is paid, thank you",
        paidBody: (businessName: string) =>
            `Your payment to ${businessName} is complete. A receipt will follow from the business.`,
        interacStartError: "We couldn't start the Interac payment. Please try again.",
        cardStartError: "We couldn't start the card payment. Please try again.",
        credit: (method: string, when: string) => `${method}, ${when}`,
        depositCredit: "Deposit you paid when booking",
        method: {
            card: "Card",
            cash: "Cash",
            interac: "Interac e-Transfer",
            bank_eft: "Bank debit",
            cheque: "Cheque",
            other: "Payment",
        } as Record<string, string>,
        downloadInvoice: "Download invoice",
        statusLabel: {
            sent: "Sent",
            partial: "Partly paid",
            overdue: "Overdue",
            paid: "Paid",
            refunded: "Refunded",
            void: "Void",
        } as Record<string, string>,
        poweredBy: "Sent with Clientbridge",
        closePrint: "Close",
    },
    publicEstimate: {
        notFoundTitle: "This estimate is no longer available",
        notFoundBody:
            "The link may be old, or the business replaced the estimate. Ask them for a new link.",
        from: (biz: string) => `From ${biz}`,
        estimate: "Estimate",
        estimateNumber: (n: number) => `Estimate #${n}`,
        preparedFor: (client: string) => `Prepared for ${client}`,
        estimateTotal: "Estimate total",
        validUntil: (when: string) => `Valid until ${when}`,
        lines: "What's included",
        optional: "Optional",
        optionalNote: "Tick it to add it",
        subtotal: "Subtotal",
        total: "Total",
        accept: "Accept estimate",
        acceptFor: (amount: string) => `Accept for ${amount}`,
        accepting: "Accepting…",
        decline: "Decline",
        declineTitle: "Decline this estimate",
        declineReason: "Anything they should know?",
        declineReasonHint: "Optional. It goes to the business.",
        declinePlaceholder: "Timing, price, or a different service",
        sendDecline: "Send",
        cancel: "Cancel",
        acceptNote: (biz: string) =>
            `Accepting tells ${biz} to go ahead. Nothing is charged now; you'll get an invoice.`,
        acceptedTitle: "Estimate accepted",
        acceptedBody: (biz: string) => `Thanks. ${biz} has been told and will be in touch.`,
        declinedTitle: "Estimate declined",
        declinedBody: (biz: string) => `Thanks for letting ${biz} know.`,
        expiredTitle: "This estimate has expired",
        expiredBody: (biz: string) => `Ask ${biz} for an updated one.`,
        downloadPdf: "Download PDF",
        answerError: "We couldn't send your answer. Please try again.",
        poweredBy: "Sent with Clientbridge",
        closePrint: "Close",
    },
    publicBooking: {
        slotsLoadError: "We couldn't load open times. Please try another day.",
        bookError: "We couldn't book that time. It may have just been taken — try another.",
        notFoundTitle: "Booking page not found",
        notFoundBody:
            "This link is invalid or the business isn't accepting online bookings right now.",
        bookWith: "Book an appointment with",
        service: "Service",
        selectService: "Select a service",
        with: "With",
        selectStaff: "Select a team member",
        date: "Date",
        yourName: "Your name",
        fullNamePlaceholder: "Full name",
        email: "Email",
        emailPlaceholder: "you@example.com",
        phone: "Phone",
        phonePlaceholder: "(555) 555-5555",
        reachYouNote: "Add an email or phone so the business can reach you.",
        depositRequired: (amount: string) =>
            `A deposit of ${amount} is required to confirm this booking.`,
        booking: "Booking…",
        confirmBooking: "Confirm booking",
        durationSuffix: (min: number) => ` · ${min} min`,
        anyAvailable: "Any available",
        openTimes: "Open times",
        loadingTimes: "Loading times…",
        noOpenTimes: "No open times that day. Try another date.",
        theDeposit: "the deposit",
        holdSpotTitle: "Hold your spot",
        holdSpotBody: (businessName: string, amount: string) =>
            `Your time with ${businessName} is reserved. Pay the ${amount} deposit to confirm it.`,
        bookedTitle: "You're booked",
        bookedBody: (businessName: string) =>
            `Your appointment with ${businessName} is confirmed. They'll be in touch with any details.`,
        depositLinkNote:
            "A deposit is required to hold this booking — a secure payment link will follow by email or text.",
        incompleteForm: "Add your name and an email or phone, then pick a time.",
        addonsTitle: "Add to your visit",
        addonsNote: "Optional. Paid with your visit, not now.",
        addonsTotal: (amount: string) => `Add-ons: ${amount}, paid at your visit`,
        shopLink: "Shop products",
    },
    publicShop: {
        notFoundTitle: "Shop not found",
        notFoundBody: "This link is invalid or the business isn't selling online right now.",
        title: (business: string) => `Shop ${business}`,
        subtitle: "Pay online and collect your order in person.",
        empty: "Nothing is for sale online right now.",
        outOfStock: "Out of stock",
        quantity: "quantity",
        add: "Add",
        cart: "Your order",
        cartEmpty: "Add something to start an order.",
        subtotal: "Subtotal",
        taxNote: "Tax is added at checkout.",
        yourDetails: "Your details",
        name: "Your name",
        email: "Email",
        phone: "Phone",
        reachYouNote: "Add an email or phone so the business can tell you when it's ready.",
        placeOrder: "Continue to payment",
        placing: "Placing order…",
        payTitle: "Pay for your order",
        total: (amount: string) => `Total ${amount}, tax included`,
        payNow: (amount: string) => `Pay ${amount}`,
        paying: "Paying…",
        back: "Back to your order",
        paidTitle: "Order placed",
        paidBody: (business: string) =>
            `${business} has your order. They'll let you know when it's ready to pick up.`,
        notTakingPayments: "This shop isn't taking online payments right now.",
        incomplete: "Add a product, your name and an email or phone.",
        orderError: "We couldn't place the order. Please try again.",
    },
    navigation: {
        createMenu: "Create",
        search: "Search",
        searchShortcut: "⌘K",
        notifications: "Notifications",
        businessMenu: "Open business settings",
        accountMenu: "Account menu",
        main: "Main",
        finishSetup: "Finish setting up",
        setupProgress: (done: number, total: number) =>
            `${String(done)} of ${String(total)} set up`,
        recentClients: "Book again",
        yourHours: "Your hours",
        bookAgain: (name: string) => `Book ${name}`,
        more: "More",
        createActions: {
            booking: { label: "Booking", hint: "Book a client into a service or class" },
            sale: { label: "Sale", hint: "Ring up services and products" },
            invoice: { label: "Invoice", hint: "Bill a client and send a pay link" },
            estimate: { label: "Estimate", hint: "Quote a job before booking it" },
            client: { label: "Client", hint: "Add someone new to your client list" },
            message: { label: "Message", hint: "Text or email a client" },
            timeOff: { label: "Time off", hint: "Change your hours or block a day" },
        },
        newBooking: "New booking",
        newSale: "New sale",
        today: "Today",
        schedule: "Schedule",
        clients: "Clients",
        payments: "Payments",
        inbox: "Inbox",
        setup: "Setup",
        signOut: "Sign out",
        paymentsTabs: {
            invoices: "Invoices",
            sales: "Sales",
            giftCards: "Gift cards",
            staffPay: "Staff pay",
            reports: "Reports",
        },
        setupSections: {
            business: "Business",
            services: "Services & products",
            team: "Team & hours",
            gettingPaid: "Getting paid",
            onlineBooking: "Online booking",
        },
        inboxSegments: {
            messages: "Messages",
            reviews: "Reviews",
        },
    },
    publicContract: {
        sign: "Sign contract",
        signedStatus: "Contract signed",
        declinedStatus: "Contract declined",
        fullNamePlaceholder: "Full legal name",
        signedThanks: (contractName: string, businessName: string) =>
            `Thank you. Your signature on “${contractName}” for ${businessName} is recorded.`,
        declinedNote: (contractName: string, businessName: string) =>
            `You declined “${contractName}”. Contact ${businessName} if this was a mistake.`,
        notFoundTitle: "Contract not found",
        notFoundBody:
            "This signing link is invalid or has expired. Please check with the business that sent it to you.",
        typeNameToSign: "Type your full name to sign",
        uploadSignature: "Or upload a signature image",
        attached: (name: string) => `Attached: ${name}`,
        decline: "Decline",
        esignConsent:
            "By typing your name and signing, you agree this is your electronic signature.",
        signatureUploadFailedDetail: "the signature upload failed",
        signPrompt: "Type your full name or upload a signature image to sign.",
        signError: "We couldn't record your signature. Please try again.",
        signatureUploadError: "We couldn't upload that signature image. Please try again.",
        recordError: "We couldn't record that. Please try again.",
    },
    publicForm: {
        submitting: "Submitting…",
        submit: "Submit",
        notFoundTitle: "Form not found",
        notFoundBody:
            "This link is invalid or has expired. Please check with the business that sent it to you.",
        fileAttached: "File attached ✓",
        selectPlaceholder: "Select…",
        doneTitle: "Thanks — all done",
        doneBody: (businessName: string) => `Your responses have been sent to ${businessName}.`,
        fileUploadFailedDetail: "the file upload failed",
        answerRequired: (label: string) => `“${label}” is required.`,
        fileUploadError: "We couldn't upload that file. Please try again.",
        submitAnswersError: "We couldn't submit your answers. Please try again.",
    },
    publicReview: {
        prompt: (businessName: string) => `How was your experience with ${businessName}?`,
        ratingLabel: "Your rating",
        notePlaceholder: "Add a note (optional)",
        submit: "Submit review",
        submitting: "Submitting…",
        pickRating: "Please pick a rating.",
        submitError: "Couldn't submit your review. Please try again.",
        notFoundTitle: "Review not found",
        notFoundBody:
            "This link is invalid or has expired. Please check with the business that sent it to you.",
        doneTitle: "Thanks for the feedback",
        doneBody: (businessName: string) => `Your review has been shared with ${businessName}.`,
    },
    publicLanding: {
        book: "Book an appointment",
        servicesTitle: "Services",
        notFoundTitle: "Business not found",
        notFoundBody: "This link is invalid or the business is no longer taking bookings here.",
        pageNotFoundTitle: "Page not found",
        pageNotFoundBody: "Check the link the business sent you, or contact them directly.",
    },
    files: {
        uploadFile: "Upload file",
        uploading: "Uploading…",
        viewUploadedFile: "View uploaded file",
        pickerNotWired: "File picker not wired in this build.",
        uploaded: "Uploaded.",
        changeImage: "Change image",
        logo: "Logo",
        uploadLogo: "Upload logo",
        replaceLogo: "Replace logo",
    },
    checkout: {
        payment: "Payment",
        newCard: "Pay with a new card",
        selectSavedMethod: "Select a saved method",
        chooseSavedMethod: "Choose a saved payment method.",
        addMethodFirst: "Add a payment method to the client first.",
        notConfiguredSavedCard: "Card payments aren’t configured. Charge a saved card instead.",
        notConfiguredContact: "Card payments aren't configured. Please contact the business.",
        back: "Back",
        paymentFailed: "Payment failed. Please try again.",
        charging: "Charging…",
        charge: (amount: string) => `Charge ${amount}`,
        pay: (amount: string) => `Pay ${amount}`,
        saveError: "Couldn’t save the card. Please check the details and try again.",
        saveCard: "Save card",
    },
    search: {
        placeholder: "Search",
        recent: "Recent",
        clearRecent: "Clear",
        jumpTo: "Go to",
        actions: "Actions",
        clients: "Clients",
        bookings: "Bookings",
        invoices: "Invoices",
        items: "Services and products",
        all: "All",
        filters: "Filter results",
        noResults: (q: string) => `Nothing matches “${q}”.`,
        noResultsHint: "Try a phone number, an email or an invoice number.",
        addClientNamed: (q: string) => `Add “${q}” as a new client`,
        bookFor: (name: string) => `Book ${name}`,
        messageTo: (name: string) => `Message ${name}`,
        bookingLine: (item: string, when: string, staff: string) => `${item} · ${when} · ${staff}`,
        invoiceNumber: (n: number) => `#${String(n)}`,
        draftInvoice: "Draft invoice",
        invoiceLine: (client: string, amount: string) => `${client} · ${amount}`,
        minutes: (n: number) => `${String(n)} min`,
        navigate: "to move",
        open: "to open",
        close: "to close",
        esc: "esc",
        offline: "Searching what’s on this device. Everything synced is included.",
        seeAll: (n: number) => `See all ${String(n)}`,
        recentSearch: (q: string) => `Search again for ${q}`,
        cancel: "Cancel",
        loading: "Getting this device ready to search",
        loadError: "Couldn’t search this device",
        loadErrorBody:
            "The local copy of your data didn’t open. Try again, or sign out and back in if it keeps happening.",
        nothingYet: "Nothing to search yet",
        nothingYetBody:
            "Clients, bookings and invoices show up here once you add them or they sync to this device.",
    },
    notifications: {
        title: "Notifications",
        markAllRead: "Mark all read",
        all: "All",
        unread: "Unread",
        unreadCount: (n: number) => `Unread ${String(n)}`,
        filterBy: "Show",
        groups: { today: "Today", yesterday: "Yesterday", earlier: "Earlier this week" },
        empty: "You’re all caught up.",
        emptyUnread: "No unread notifications.",
        emptyHint: "New bookings, payments and messages show up here.",
        loading: "Loading notifications",
        unreadLabel: (title: string, body: string) => `Unread: ${title}. ${body}`,
        readLabel: (title: string, body: string) => `${title}. ${body}`,
        someone: "A client",
        kinds: {
            payment: "Payment received",
            paymentBody: (client: string, amount: string) => `${client} paid ${amount}`,
            deposit: "Deposit received",
            depositBody: (client: string, amount: string) => `${client} paid a ${amount} deposit`,
            refund: "Refund sent",
            refundBody: (client: string, amount: string) => `${amount} back to ${client}`,
            bookingNew: "New online booking",
            bookingCanceled: "Booking cancelled",
            bookingBody: (client: string, item: string, when: string) =>
                when ? `${client}, ${item}, ${when}` : `${client}, ${item}`,
            message: (client: string) => `Message from ${client}`,
            review: (stars: number) => `New ${String(stars)}-star review`,
            reviewBody: (client: string, body: string) => `${client}: “${body}”`,
            overdue: (n: number) => `Invoice #${String(n)} is overdue`,
            overdueBody: (client: string) => `${client} hasn’t paid yet`,
        },
    },
    sync: {
        offlineTitle: "You’re offline",
        offlineStrip: (n: number) =>
            n === 0
                ? "Changes you make are saved on this device and sync when you reconnect"
                : n === 1
                  ? "1 change will sync when you reconnect"
                  : `${String(n)} changes will sync when you reconnect`,
        lastSynced: (time: string) => `Last synced at ${time}`,
        retry: "Try again",
        signOutTitle: "Sign out with changes not synced?",
        signOutBody: (n: number) =>
            n === 1
                ? "1 change is only on this device. If you sign out before reconnecting, it will be lost."
                : `${String(n)} changes are only on this device. If you sign out before reconnecting, they will be lost.`,
        signOutListTitle: "These changes will be lost",
        signOutSafe: "Reconnect first and they sync on their own.",
        signOutConfirm: "Sign out anyway",
        signOutCancel: "Stay signed in",
        gettingStarted: "Getting started",
        stepsDone: (done: number, total: number) => `${String(done)} of ${String(total)} done`,
        start: "Start",
        changed: (kind: string) => `${kind} changed`,
        removed: (kind: string) => `${kind} removed`,
        tables: {
            hours: "Working hours",
            forms: "A form",
            fields: "A form question",
            contracts: "A contract",
            other: "A record",
        },
    },
} as const;
