// Every user-facing string, shared by web and mobile.

export const strings = {
    common: {
        appName: "Clientbridge",
        somethingWrongRetry: "Something went wrong. Please try again.",
        fileUploadError: "Couldn't upload that file. Please try again.",
        loading: "Loading…",
        saved: "Saved.",
        save: "Save changes",
        saving: "Saving…",
        cancel: "Cancel",
        done: "Done",
        close: "Close",
        somethingWrong: "Something went wrong",
        tryAgainLater: "Please try again later.",
        working: "Working…",
        busyEllipsis: "…",
        optional: "(optional)",
        decrease: (label: string) => `Decrease ${label}`,
        increase: (label: string) => `Increase ${label}`,
        stars: (n: number) => `${n} star${n === 1 ? "" : "s"}`,
        ratingOf: (n: number) => `${n} out of 5`,
        stillSyncing: "Still syncing — try again in a moment.",
        relativeTime: {
            justNow: "just now",
            minutes: (n: number) => `${n}m`,
            hours: (n: number) => `${n}h`,
            days: (n: number) => `${n}d`,
        },
    },
    ui: {
        clearSearch: "Clear search",
        clear: "Clear",
        copy: "Copy",
        copied: "Copied",
        remove: "Remove",
        removeTag: (tag: string) => `Remove ${tag}`,
        createTag: (text: string) => `Add "${text}"`,
        previous: "Previous",
        next: "Next",
        done: "(done)",
        withCount: (label: string, count: string) => `${label}, ${count}`,
        onTicket: (name: string, count: number) => `${name}, ${count} on ticket`,
        startOf: (day: string) => `${day} start`,
        endOf: (day: string) => `${day} end`,
        cardFallback: "CARD",
        listError: "This list didn't load.",
        listErrorBody: "Check your connection, then try again.",
        retry: "Try again",
    },
    billing: {
        actionSend: "Send",
        actionVoid: "Void",
        actionAccept: "Accept",
        actionDecline: "Decline",
        actionConvert: "Convert to invoice",
        removeLine: "Remove line",
        countSummary: (invoices: number, estimates: number) =>
            `${invoices} invoices · ${estimates} estimates`,
        newButton: (noun: string) => `New ${noun}`,
        newShort: "New",
        tabInvoices: "Invoices",
        tabEstimates: "Estimates",
        searchPlaceholder: (tab: string) => `Search ${tab}…`,
        searchEmpty: (tab: string) => `No ${tab} match your search.`,
        empty: (tab: string) => `No ${tab} yet.`,
        colNumber: "#",
        colClient: "Client",
        colStatus: "Status",
        colTotal: "Total",
        draftRow: "Draft",
        clientLabel: "Client",
        clientPlaceholder: "Select a client",
        linesLabel: "Lines",
        lineDescription: "Description",
        lineQty: "Qty",
        linePrice: "Price",
        lineDescriptionPlaceholder: "Service or item",
        linePricePlaceholder: "0.00",
        addLine: "+ Add line",
        notesLabel: "Notes",
        notesPlaceholder: "Optional",
        subtotal: "Subtotal",
        plusTax: " + tax",
        saveDraft: "Save draft",
        saveChanges: "Save changes",
        edit: "Edit",
        editTitle: (noun: string) => `Edit ${noun}`,
        fromCatalog: "Add from catalog",
        invoiceHeading: "Invoice",
        estimateHeading: "Estimate",
        draftHeading: "(draft)",
        tax: "Tax",
        total: "Total",
        actionError: (action: string) => `Couldn't ${action} — please try again.`,
        payLink: "Pay link",
        copy: "Copy",
        copied: "Copied",
        share: "Share",
        payments: "Payments",
        refundBadge: "Refund",
        refund: "Refund",
        refunding: "Refunding…",
        refundingShort: "…",
        refundTitle: "Refund payment",
        refundConfirm: "Refund this payment? This can't be undone.",
        refundAmountPlaceholder: (remaining: string) => `Up to ${remaining}`,
        refundAmountInvalid: "Enter an amount up to what's left to refund.",
        refundError: "Couldn't refund this payment. Please try again.",
        incompleteInvoice: "Pick a client and add at least one line.",
        saveError: "Could not save — please try again.",
    },
    pos: {
        addItemFirst: "Add an item before charging.",
        totalError: "Couldn't total this sale. Please try again.",
        chargeStartError: "Couldn't start the charge. Please try again.",
        voidError: "Couldn't void this sale. Please try again.",
        subtitle: "Ring up a sale.",
        quantity: "quantity",
        removeLine: "Remove line",
        searchPlaceholder: "Search catalog…",
        searchEmpty: "No items match your search.",
        emptyCatalog: "No sellable catalog items yet.",
        empty: "No sellable items yet.",
        cart: "Cart",
        clear: "Clear",
        cartEmpty: "Tap a catalog item to add it.",
        cartEmptyStart: "Tap a catalog item to start a sale.",
        unitEach: (money: string) => `${money} each`,
        subtotal: "Subtotal",
        tax: "Tax",
        total: "Total",
        plusTax: " + tax",
        charge: (money: string) => `Charge ${money}`,
        collect: (money: string) => `Collect ${money}`,
        totalling: "Totalling…",
        reviewTotal: "Review total",
        clientLabel: "Client",
        receiptEmail: "Email receipt to",
        receiptPhone: "Text receipt to",
        receiptHint: "Optional. A client's sale also goes to the client's own contact details.",
        receiptEmailInvalid: "Enter a valid email for the receipt",
        payCard: "Take card payment",
        paying: "Charging…",
        payError: "Couldn't take the payment. Please try again.",
        paidTitle: "Paid",
        paidBody: (money: string) => `${money} received. The receipt is on its way.`,
        tapToPayAmount: (amount: string) => `Tap to Pay · ${amount}`,
        saleDetails: (client: string, open: boolean) => `Client: ${client}  ${open ? "−" : "+"}`,
        alsoSell: "Also sell",
        sellGiftCard: "Gift card",
        sellPackage: "Package",
        sellSubscription: "Subscription",
        chooseClient: "Choose a client first",
        readerTitle: "Charge on reader",
        readerCollect: (money: string) => `Tap, insert, or swipe the card to collect ${money}.`,
        readerRequirements:
            "Tap to Pay needs an EAS dev build + a capable device (or a simulated reader) and a Stripe Terminal location id.",
        readerConnecting: "Connecting reader…",
        readerReady: "Reader ready — tap to charge",
        readerCollecting: "Waiting for the card…",
        readerApproved: "Approved ✓",
        readerUnavailable: "Reader unavailable",
        newSale: "New sale",
        voidSale: "Void this sale",
        openOrders: "Open orders",
        walkIn: "Walk-in",
        onlineOrders: "Online orders for pickup",
        pickupUnfulfilled: "To prepare",
        pickupReady: "Ready for pickup",
        pickupDone: "Picked up",
        markReady: "Mark ready",
        markPickedUp: "Picked up",
        pickupError: "Couldn't update this order. Please try again.",
    },
    earnings: {
        subtitle: "Approve staff earnings, then mark them paid out.",
        filterTab: (filter: string, count: number) =>
            `${filter.charAt(0).toUpperCase()}${filter.slice(1)} (${String(count)})`,
        empty: (filter: string) => `No ${filter === "all" ? "" : `${filter} `}payouts.`,
        approve: "Approve",
        approving: "Approving…",
        markPaid: "Mark paid",
        approveError: "Couldn't approve this payout. Please try again.",
        markPaidError: "Couldn't mark this payout paid. Please try again.",
        staffFallback: "Staff",
        sourceBooking: "Booking",
        sourceSale: "Sale commission",
    },
    entitlements: {
        giftCards: {
            modePreset: "Preset card",
            modeCustom: "Custom amount",
            sellError: "Couldn't sell this gift card. Please try again.",
            issuedCount: (n: number) => `${n} issued`,
            redeem: "Redeem",
            redeemTitle: "Redeem gift card",
            redeeming: "Redeeming…",
            sell: "Sell gift card",
            sellShort: "Sell",
            selling: "Selling…",
            code: "Code",
            codePlaceholder: "ABCD2345EFGH",
            recipient: "Recipient",
            status: "Status",
            balance: "Balance",
            emptyList: "No gift cards issued yet.",
            ofInitial: (initial: string) => `of ${initial}`,
            amountFallback: "gift card",
            purchaser: "Purchaser",
            addClientFirst: "Add a client first.",
            type: "Type",
            giftCard: "Gift card",
            selectGiftCard: "Select a gift card",
            emptyCatalog: "No gift cards in your catalog.",
            amountCad: "Amount (CAD)",
            amountPlaceholder: "100.00",
            redeemAmountPlaceholder: "25.00",
            recipientOptional: "Recipient (optional)",
            recipientPlaceholder: "Name or email",
            selectClient: "Select a client",
            choosePurchaser: "Choose a purchaser",
            chooseGiftCard: "Choose a gift card",
            enterAmount: "Enter a gift card amount",
            enterCode: "Enter a gift card code",
            enterRedeemAmount: "Enter a redemption amount",
            redeemError: "Couldn't redeem this gift card. Please try again.",
        },
    },
    bookings: {
        eventTooltip: (time: string, title: string, subtitle: string) =>
            [time, title, subtitle].filter(Boolean).join(" · "),
        collectDepositError: "Couldn't collect the deposit. Please try again.",
        addonsTitle: "Added to this visit",
        addonsNote: "Added online by the client. They pay for these with the visit.",
        addonRemove: "Remove",
        addonRemoveError: "Couldn't remove this item. Please try again.",
        invoiceVisit: "Create invoice",
        invoiceVisitError: "Couldn't create the invoice. Please try again.",
        visitInvoiced: "This visit has an invoice.",
        seriesSkippedNotice: (created: number, skipped: number) =>
            `Booked ${created}, skipped ${skipped} (already taken or outside hours).`,
        createSeriesError: "Could not create the series. Please try again.",
        bookError: "Could not book — that time may already be taken.",
        viewDay: "Day",
        viewWeek: "Week",
        viewMonth: "Month",
        viewStaff: "Staff",
        viewAgenda: "Agenda",
        today: "Today",
        prev: "Previous",
        viewLabel: "Calendar view",
        next: "Next",
        todayPrefix: "Today · ",
        newBookingButton: "+ New booking",
        newBooking: "New booking",
        moreCount: (n: number) => `+${n} more`,
        noBookings: "No bookings",
        client: "Client",
        selectClient: "Select a client",
        service: "Service",
        selectService: "Select a service",
        staff: "Staff",
        date: "Date",
        time: "Time",
        repeatBooking: "Repeat this booking",
        every: "Every",
        frequency: "Frequency",
        occurrences: "Occurrences",
        booking: "Booking…",
        bookSeries: "Book series",
        book: "Book",
        canceling: "Canceling…",
        cancelBooking: "Cancel booking",
        deposit: "Deposit",
        collecting: "Collecting…",
        collectAmount: (amount: string) => `Collect ${amount}`,
        cancelError: "Couldn't cancel this booking. Please try again.",
        incompleteBooking: "Pick a client, service, and time.",
        freqDaily: "Daily",
        freqWeekly: "Weekly",
        freqMonthly: "Monthly",
        unitDays: "Days",
        unitWeeks: "Weeks",
        unitMonths: "Months",
        repeat: "Repeat",
        oneTime: "One-time",
    },
    forms: {
        fieldTypeText: "Short text",
        fieldTypeLongtext: "Paragraph",
        fieldTypeEmail: "Email",
        fieldTypePhone: "Phone",
        fieldTypeNumber: "Number",
        fieldTypeCurrency: "Amount",
        fieldTypeDate: "Date",
        fieldTypeTime: "Time",
        fieldTypeSelect: "Dropdown",
        fieldTypeMultiselect: "Multi-select",
        fieldTypeCheckbox: "Checkbox",
        fieldTypeAddress: "Address",
        fieldTypeRating: "Rating",
        fieldTypeFile: "File",
        fieldTypeImage: "Image",
        fieldTypeSignature: "Signature",
        ownerAdminOnly: "Only owners and admins can manage forms and contracts.",
        intro: "Build intake forms and contracts, then send them to clients to complete.",
        intakeForms: "Intake forms",
        newForm: "New form",
        sendForm: "Send form",
        sendFormTitle: "Send a form",
        emptyForms: "No forms yet. Create one to send to clients.",
        fieldCount: (n: number) => `${n} field${n === 1 ? "" : "s"}`,
        signatureRequired: " · signature required",
        form: "Form",
        selectForm: "Select a form",
        client: "Client",
        selectClient: "Select a client",
        formName: "Form name",
        formNamePlaceholder: "New client intake",
        addField: "+ Add field",
        requireSignature: "Require a signature",
        createForm: "Create form",
        fieldN: (n: number) => `Field ${n}`,
        remove: "Remove",
        fieldLabelPlaceholder: "Field label",
        fieldType: "Field type",
        optionsPlaceholder: "Options, comma separated",
        required: "Required",
        sendFormError: "Couldn't send the form. Please try again.",
        formNameRequired: "Name is required",
        addFieldError: "Add at least one field",
        saveFormError: "Couldn't save the form. Please try again.",
    },
    contracts: {
        client: "Client",
        selectClient: "Select a client",
        contracts: "Contracts",
        newContract: "New contract",
        sendForSignature: "Send for signature",
        emptyContracts: "No contracts yet. Create one to send for signature.",
        version: (n: number) => `Version ${n}`,
        contract: "Contract",
        selectContract: "Select a contract",
        send: "Send",
        secureLinkNotice:
            "The client signs on a secure link. Status appears here once they respond.",
        name: "Name",
        contractNamePlaceholder: "Service agreement",
        contractText: "Contract text",
        contractTextPlaceholder: "Paste or write the contract the client will sign…",
        createContract: "Create contract",
        sendContractError: "Couldn't send the contract. Please try again.",
        contractNameRequired: "Name is required",
        contractTextRequired: "Contract text is required",
        saveContractError: "Couldn't save the contract. Please try again.",
    },
    clients: {
        sellPackageError: "Couldn't sell this package. Please try again.",
        title: "Clients",
        total: (count: number) => `${count} total`,
        add: "Add client",
        addShort: "Add",
        searchPlaceholder: "Search clients…",
        colName: "Name",
        colPhone: "Phone",
        colStatus: "Status",
        colLifetime: "Lifetime",
        dash: "—",
        empty: "No clients yet.",
        emptySearch: "No clients match your search.",
        manageRestricted:
            "Only owners and admins can manage payment methods, subscriptions, and packages.",
        paymentMethods: "Payment methods",
        noPaymentMethods: "No saved payment methods yet.",
        starting: "Starting…",
        addCard: "Add card",
        addBankWeb: "Add bank (pre-authorized debit)",
        setDefaultError: "Couldn't set the default. Please try again.",
        removeMethodTitle: "Remove payment method",
        removeMethodConfirm: "Remove this payment method?",
        removeMethodError: "Couldn't remove this method. Please try again.",
        defaultTag: "Default",
        makeDefault: "Make default",
        remove: "Remove",
        cardNoun: "card",
        bankAccountNoun: "bank account",
        saveMethod: (noun: string) => `Save ${noun}`,
        subscriptions: "Subscriptions",
        startSubscriptionLink: "+ Start subscription",
        noSubscriptions: "No subscriptions yet.",
        subscriptionFallback: "Subscription",
        nextCharge: (date: string) => `Next charge ${date}`,
        cancelSubscriptionTitle: "Cancel subscription",
        cancelSubscriptionConfirm: "Cancel this subscription?",
        cancelSubscriptionError: "Couldn't cancel this subscription. Please try again.",
        keep: "Keep",
        canceling: "Canceling…",
        planLabel: "Plan",
        selectPlan: "Select a subscription plan",
        addSubscriptionItemFirst: "Add a subscription item in your catalog first.",
        startSubscription: "Start subscription",
        packages: "Packages",
        sellPackageLink: "+ Sell package",
        noPackages: "No packages yet.",
        packageFallback: "Package",
        packageAmountFallback: "package",
        consumeSessionError: "Couldn't consume a session. Please try again.",
        sessionsLeft: (remaining: number, total: number) =>
            `${remaining} of ${total} sessions left`,
        sessionsLeftShort: (remaining: number, total: number) => `${remaining} of ${total} left`,
        consumeSession: "Consume session",
        consumeShort: "Consume",
        packageLabel: "Package",
        selectPackage: "Select a package",
        addPackageItemFirst: "Add a package item in your catalog first.",
        sellPackage: "Sell package",
        selling: "Selling…",
        addClientTitle: "Add client",
        nameLabel: "Name",
        emailLabel: "Email",
        phoneLabel: "Phone",
        adding: "Adding…",
        addClient: "Add client",
        nameRequired: "Name is required",
        addError: "Could not add client",
        choosePackage: "Choose a package",
        choosePlan: "Choose a subscription plan",
        startSubscriptionError: "Couldn't start the subscription. Please try again.",
    },
    messaging: {
        channelSms: "Text",
        channelEmail: "Email",
        channelChat: "Chat",
        title: "Inbox",
        subtitle: "Message clients and send broadcasts.",
        broadcast: "Broadcast",
        newMessage: "New message",
        newShort: "New",
        noConversations: "No conversations yet.",
        selectConversation: "Select a conversation to read and reply.",
        clientFallback: "Client",
        noMessages: "No messages yet.",
        replyBy: (channel: string) => `Reply by ${channel}…`,
        send: "Send",
        sending: "Sending…",
        newMessageTitle: "New message",
        clientLabel: "Client",
        selectClient: "Select a client",
        addClientFirst: "Add a client first.",
        channelLabel: "Channel",
        messageLabel: "Message",
        messagePlaceholder: "Write a message…",
        sendMessage: "Send message",
        broadcastScheduled: "Broadcast scheduled",
        broadcastSent: "Broadcast sent",
        broadcastRecipients: (name: string, count: number) =>
            `${name} · ${count} recipient${count === 1 ? "" : "s"}.`,
        broadcastRecipientsShort: (name: string, count: number) =>
            `${name} · ${count} recipient${count === 1 ? "" : "s"}`,
        newBroadcastTitle: "New broadcast",
        nameLabel: "Name",
        namePlaceholder: "Spring promo",
        announcementPlaceholder: "Write your announcement…",
        audienceTagsLabel: "Audience tags",
        audienceTagsOptional: "Audience tags (optional)",
        optional: "(optional)",
        tagsPlaceholderWeb: "vip, regulars — leave blank for everyone",
        tagsPlaceholderShort: "vip, regulars — blank = everyone",
        scheduleLabel: "Schedule",
        sendBroadcast: "Send broadcast",
        writeMessage: "Write a message",
        sendError: "Couldn't send your message. Please try again.",
        nameBroadcast: "Name your broadcast",
        broadcastError: "Couldn't send the broadcast. Please try again.",
    },
    reviews: {
        postReplyError: "Couldn't post your reply. Please try again.",
        hideError: "Couldn't hide this review. Please try again.",
        publishError: "Couldn't publish this review. Please try again.",
        sendRequestError: "Couldn't send the review request. Please try again.",
        subtitle: "Reply to feedback and choose what shows publicly.",
        requestReview: "Request review",
        noReviews: "No reviews yet.",
        loadingRating: "Loading rating…",
        ratingLoadError: "Couldn't load your rating.",
        noPublishedReviews: "No published reviews yet.",
        publishedCount: (count: number) => `${count} published review${count === 1 ? "" : "s"}`,
        awaitingCount: (count: number) =>
            `${count} request${count === 1 ? "" : "s"} waiting for a reply`,
        clientFallback: "Client",
        yourReply: "Your reply",
        replyPlaceholder: "Write a public reply…",
        postReply: "Post reply",
        editReply: "Edit reply",
        reply: "Reply",
        publish: "Publish",
        hide: "Hide",
        requestTitle: "Request a review",
        clientLabel: "Client",
        selectClient: "Select a client",
        addClientFirst: "Add a client first.",
        sending: "Sending…",
        sendRequest: "Send request",
    },
    business: {
        subtitle: "Your business profile and tax registration.",
        language: "Language",
        nameLabel: "Business name",
        namePlaceholder: "Birch Bark Pet Care",
        timezoneLabel: "Time zone",
        timezonePlaceholder: "America/Toronto",
        billingEmailLabel: "Billing email",
        billingEmailPlaceholder: "you@example.com",
        gstLabel: "GST/HST number",
        gstPlaceholder: "123456789RT0001",
        qstLabel: "QST number",
        qstPlaceholder: "1234567890TQ0001",
        nameRequired: "Business name is required",
        saveError: "Could not save account settings",
        brandTitle: "Brand",
        brandSubtitle: "Shown to your clients on booking, pay, and other links.",
        primaryLabel: "Primary colour",
        primaryPlaceholder: "#3F5E80",
        taglineLabel: "Tagline",
        taglinePlaceholder: "Calm, careful grooming on the island.",
        onboarding: {
            provinceAB: "Alberta",
            provinceBC: "British Columbia",
            provinceMB: "Manitoba",
            provinceNB: "New Brunswick",
            provinceNL: "Newfoundland and Labrador",
            provinceNS: "Nova Scotia",
            provinceNT: "Northwest Territories",
            provinceNU: "Nunavut",
            provinceON: "Ontario",
            provincePE: "Prince Edward Island",
            provinceQC: "Quebec",
            provinceSK: "Saskatchewan",
            provinceYT: "Yukon",
            settingUp: "Setting up your workspace…",
            title: "Create your business",
            subtitleWeb:
                "Tell us about your practice — we’ll set up your bookings, invoices, and the right tax rates for your province.",
            subtitleMobile:
                "We’ll set up your bookings, invoices, and the right tax rates for your province.",
            businessName: "Business name",
            businessNamePlaceholder: "Birch Bark Pet Care",
            webAddress: "Web address",
            slugPrefix: "clientbridge.ca/",
            slugPlaceholder: "birch-bark",
            province: "Province",
            creating: "Creating…",
            createBusiness: "Create business",
            notYou: "Not you?",
            signOut: "Sign out",
            notYouSignOut: "Not you? Sign out",
            nameRequired: "Business name is required",
            slugRequired: "A web address is required",
            createError: "Couldn’t create your business — that web address may be taken.",
        },
    },
    hours: {
        title: "Working hours",
        subtitle:
            "Set each team member’s weekly working hours. Bookings are held to these windows.",
        noStaff: "No team members yet.",
        teamMember: "Team member",
        from: "Opens",
        to: "to",
        closed: "Closed",
        saveHours: "Save hours",
        startHint: "09:00",
        endHint: "17:00",
        timeFormatError: "Times must be in HH:MM format",
        timeOrderError: "Each open day needs a start time before its end time",
        saveError: "Couldn't save hours. Please try again.",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        sunday: "Sunday",
    },
    staff: {
        inviteMissingCode: "This invite link is missing its code.",
        passwordTooShort: "Choose a password of at least 8 characters.",
        acceptInviteError: "Couldn’t accept this invite — it may be invalid or expired.",
        subtitle: "Invite colleagues and manage who can access your business.",
        noMembers: "No team members yet.",
        members: "Members",
        youBadge: "You",
        youSuffix: " (You)",
        pending: "Pending invites",
        invitedBadge: (role: string) => `${role} · invited`,
        cannotInvite: "Only owners and admins can invite teammates.",
        inviteHeading: "Invite a teammate",
        email: "Email",
        emailPlaceholder: "teammate@example.com",
        role: "Role",
        inviting: "Inviting…",
        sendInvite: "Send invite",
        inviteSentWeb: (email: string) =>
            `Invite sent to ${email}. Share this link so they can join:`,
        inviteSentMobile: (email: string) => `Invite sent to ${email}. Share this link:`,
        copied: "Copied",
        copy: "Copy",
        shareLink: "Share link",
        emailRequired: "An email is required",
        inviteError: "Couldn’t send that invite — check the email and try again.",
        roleStaff: "Staff",
        roleAdmin: "Admin",
        roleContractor: "Contractor",
        payHeading: "Pay",
        isPayee: "Pay this member through Staff pay",
        rateType: "Paid for services by",
        ratePercent: "Percent of the service price",
        rateFixed: "Fixed amount per booking",
        rateHourly: "Hourly rate",
        rateLabel: (type: string) =>
            type === "percent" ? "Rate (%)" : type === "hourly" ? "Rate ($ per hour)" : "Rate ($)",
        retailRate: "Commission on products sold (%)",
        rateInvalid: "Enter a rate of 0 or more (a percentage can't be over 100)",
        retailInvalid: "Enter a commission between 0 and 100",
        payError: "Couldn't save this member's pay",
        notPaid: "Not paid through Staff pay",
        payPercent: (rate: number) => `${String(rate)}% of services`,
        payFixed: (money: string) => `$${money} per booking`,
        payHourly: (money: string) => `$${money} an hour`,
        payWithRetail: (service: string, retail: number) =>
            `${service} · ${String(retail)}% on products`,
    },
    catalog: {
        kindService: "Service",
        kindProduct: "Product",
        kindClass: "Class",
        kindPackage: "Package",
        kindSubscription: "Subscription",
        kindGift: "Gift card",
        nameRequired: "Name is required",
        addError: "Could not add item",
        itemCount: (n: number) => `${String(n)} items`,
        addItem: "Add item",
        searchPlaceholder: "Search catalog…",
        name: "Name",
        type: "Type",
        duration: "Duration",
        price: "Price",
        durationMin: (n: number) => `${String(n)} min`,
        durationSep: (n: number) => ` · ${String(n)} min`,
        noMatch: "No items match your search.",
        filterEmpty: "Nothing here right now.",
        empty: "No catalog items yet.",
        priceLabel: "Price ($)",
        durationLabel: "Duration (min)",
        category: "Category",
        adding: "Adding…",
        description: "Description",
        taxStandard: "Standard (all taxes for your province)",
        taxFederalOnly: "GST or HST only",
        taxExempt: "Exempt",
        taxClass: "Sales tax",
        taxNote:
            "Which taxes apply depends on what you sell and where. Confirm with your accountant.",
        depositNone: "No deposit",
        depositFixed: "Fixed amount",
        depositPercent: "Percent of price",
        depositType: "Deposit",
        depositAmount: "Deposit ($)",
        depositPercentLabel: "Deposit (%)",
        freqWeek: "Every week",
        freqMonth: "Every month",
        freqYear: "Every year",
        repeatsEvery: "Bills every",
        intervalLabel: "Interval",
        bufferBefore: "Buffer before (min)",
        bufferAfter: "Buffer after (min)",
        capacity: "Class size",
        onlineBookable: "Clients can book this online",
        sessionCount: "Visits in the package",
        validityDays: "Valid for (days)",
        validityHint: "Leave blank for no expiry.",
        sku: "SKU",
        cost: "Cost ($)",
        trackStock: "Track stock",
        sellOnline: "Sell in the online shop",
        openingStock: "Stock on hand",
        lowStockAt: "Warn when stock is at or below",
        stockOut: "Out of stock",
        stockLow: (n: number) => `Low: ${String(n)} left`,
        stockIn: (n: number) => `${String(n)} in stock`,
        filterAll: "All",
        filterLowStock: "Low stock",
        filterArchived: "Archived",
        priceInvalid: "Enter a price like 45 or 45.00",
        durationRequired: "Set how long it takes, in minutes",
        depositRequired: "Enter the deposit amount",
        depositPercentMax: "A percentage deposit can't be over 100",
        sessionsRequired: "Set how many visits the package includes",
        intervalRequired: "Set how often it bills",
        stockInvalid: "Stock on hand must be a whole number",
        openingStockNote: "Opening stock",
        saveError: "Could not save the item",
        newItem: "New item",
        save: "Save",
        saving: "Saving…",
        archive: "Archive",
        restore: "Restore",
        archivedPill: "Archived",
        restock: "Restock",
        restockQuantity: "Quantity",
        restockQuantityHint: "Use a negative number to correct a miscount.",
        restockNote: "Note (optional)",
        restocking: "Saving…",
        restockInvalid: "Enter a whole number other than zero",
        restockError: "Could not update stock",
        stockHeading: "Stock",
    },
    taxes: {
        title: "Taxes",
        subtitle: "Sales tax applied to your invoices, based on your province.",
        empty: "No tax rates set for your province yet.",
        colTax: "Tax",
        colProvince: "Province",
        footnote:
            "Rates are seeded per province; small-supplier and registration settings come with the payments slice.",
    },
    payments: {
        setupStartError: "Couldn't start payment setup. Please try again.",
        bankAccountNoun: "Bank account",
        cardNoun: "Card",
        interacNoun: "Interac e-Transfer",
        savedCardLabel: (noun: string, last4: string) => `${noun} ···· ${last4}`,
    },
    gettingPaid: {
        reqExternalAccount: "Bank account for payouts",
        reqBusinessWebsite: "Business website",
        reqBusinessCategory: "Business category",
        reqProductDescription: "What you sell",
        reqIdNumber: "ID number (SIN)",
        reqPhotoId: "Photo ID",
        reqProofOfAddress: "Proof of address",
        reqHomeAddress: "Home address",
        reqBusinessNumber: "Business number",
        reqTosAcceptance: "Accept Stripe's terms",
        reqDateOfBirth: "Date of birth",
        headlineNotConnected: "Connect Stripe to take card payments and get paid out.",
        headlineInProgress: "Onboarding in progress — finish your Stripe setup.",
        headlinePending:
            "Stripe is reviewing your details. No action needed — this updates automatically.",
        headlineRestricted: "Stripe needs a bit more to keep your payments active:",
        headlineEnabled: "Payments enabled — you can take card payments.",
        headlineDisabled:
            "Your Stripe account can't accept payments right now. Please contact support.",
        finishVerification: "Finish verification",
        continueSetup: "Continue setup",
        connectStripe: "Connect Stripe",
        onboardingStartError: "Couldn't start Stripe onboarding. Please try again.",
        subtitle: "Take card payments through Stripe and get paid out to your bank.",
        loadError: "We couldn’t load your payment status. Please try again.",
        tryAgain: "Try again",
        opening: "Opening…",
        payoutsActive: "Connected to Stripe. Payouts are active.",
        payoutsPending: "Connected to Stripe. Payouts start once your bank details are verified.",
    },
    today: {
        connected: "connected",
        offline: "offline",
        activityRefund: "Refund",
        activityDepositReceived: "Deposit received",
        activityInteracReceived: "Interac received",
        activityCardPayment: "Card payment",
        activityPayment: "Payment",
        title: "Today",
        staffSubtitle: "Your bookings are on the Schedule.",
        moneySubtitle: "Your money at a glance.",
        numbersError: "Couldn’t load your numbers.",
        todayRevenue: "Today's revenue",
        todayRevenueCaption: "received today",
        awaitingPayment: "Awaiting payment",
        awaitingPaymentCaption: "outstanding invoices",
        gstSetAside: "GST/HST set aside",
        gstSetAsideCaption: "remit to CRA",
        recentActivity: "Recent activity",
        noPayments: "No payments yet.",
    },
    reports: {
        subtitle: "Income, GST/HST, and T4A — export for your bookkeeper or the CRA.",
        loadError: "Couldn’t load your reports.",
        rangeFrom: "From",
        rangeTo: "To",
        t4aYear: "T4A year",
        incomeTitle: "Income",
        bankDeposits: "Bank deposits",
        bankDepositsSubtitle: "Stripe payouts to your bank account",
        noBankDeposits: "No bank deposits yet.",
        remitTitle: "Filed returns",
        remitAction: (start: string, end: string) => `Record remittance for ${start} to ${end}`,
        remitting: "Recording…",
        remitError: "Couldn't record the remittance. Please try again.",
        remitRow: (start: string, end: string) => `${start} to ${end}`,
        remitNone: "No returns filed yet.",
        incomeSubtitle: "Payments received, net of refunds",
        gross: "Gross",
        refunds: "Refunds",
        net: "Net",
        gstTitle: "GST/HST",
        gstSubtitle:
            "Federal GST/HST on issued invoices — remit to the CRA (PST/QST file separately)",
        gstSubtitleMobile: "Federal GST/HST on issued invoices",
        taxCollected: "GST/HST collected",
        pstCollected: "PST collected",
        qstCollected: "QST collected",
        taxableSales: "Taxable sales",
        gstNumberLabel: "GST/HST number",
        notRegistered: "Not registered",
        t4aTitle: (year: number) => `T4A — ${year}`,
        t4aSubtitle: "Amounts paid to staff payees for the calendar year",
        t4aSubtitleMobile: "Amounts paid to staff payees",
        noPayeeAmounts: (year: number) => `No payee amounts for ${year}.`,
        colPayee: "Payee",
        colTotal: "Total",
        downloadCsv: "Download CSV",
        downloading: "Downloading…",
        csv: "CSV",
        loadingReports: "Loading reports…",
        exportError: "Couldn't export the CSV. Please try again.",
        salesByItemTitle: "Sales by item",
        salesByItemSubtitle: "Services, classes and products sold, before tax",
        noItemSales: "No item sales in this period.",
        colItem: "Item",
        colQty: "Qty",
        colSales: "Sales",
        colTax: "Tax",
        colRefunded: "Refunded",
        qty: (n: number) => (Number.isInteger(n) ? String(n) : n.toFixed(2)),
    },
    auth: {
        invalidCredentials: "Invalid email or password",
        createAccountError: "Could not create that account — try another email",
        heroHeadlineLine1: "The bridge between you",
        heroHeadlineLine2: "and your clients.",
        heroSubtitle:
            "Bookings, invoices, payments, and messaging — synced to every device, online or off. Built for service pros.",
        heroFeatures: ["Scheduling", "Invoicing", "Payments", "GST/HST"],
        signInTitle: "Sign in",
        signUpTitle: "Create your account",
        signInSubtitle: "Welcome back.",
        signUpSubtitle: "Start running your practice in minutes.",
        name: "Name",
        namePlaceholder: "Hannah Bauer",
        email: "Email",
        emailPlaceholder: "you@example.com",
        password: "Password",
        passwordPlaceholder: "••••••••",
        signingIn: "Signing in…",
        creatingAccount: "Creating account…",
        signIn: "Sign in",
        createAccount: "Create account",
        or: "or",
        continueWithGoogle: "Continue with Google",
        newToApp: "New to Clientbridge?",
        haveAccount: "Already have an account?",
        createAnAccount: "Create an account",
        inviteTitle: "Accept your invite",
        inviteSubtitle: "Set a password to join your team and start collaborating.",
        inviteMissingCode:
            "This invite link is missing its code. Please use the link from your email.",
        inviteName: "Your name",
        joining: "Joining…",
        joinTeam: "Join team",
        googleNotConfigured: "Google sign-in isn’t configured yet — use email & password.",
    },
    publicPay: {
        notFoundTitle: "Invoice not found",
        notFoundBody:
            "This payment link is invalid or has expired. Please check with the business that sent it to you.",
        cardNotConfigured: "Card payments aren't configured. Please use Interac e-Transfer.",
        requestingPayment: (businessName: string) => `${businessName} is requesting payment`,
        invoice: "Invoice",
        invoiceNumber: (n: number) => `Invoice #${n}`,
        balanceDue: "Balance due",
        ofTotal: (total: string) => `of ${total} total`,
        chooseHowToPay: "Choose how to pay",
        interacLabel: "Interac e-Transfer",
        interacBadge: "Recommended · no fee",
        cardLabel: "Credit or debit card",
        payByInterac: "Pay by Interac",
        payByCard: "Pay by card",
        interacHeading: "Send your Interac e-Transfer",
        interacSendPrefix: "Send an Interac e-Transfer of",
        interacTo: "to",
        interacAndPut: "and put",
        interacInMessage: "in the message.",
        interacNoEmail: "The business will share their e-Transfer email with you. Send",
        interacConfirmNote:
            "Your payment will be marked as received once the business confirms the transfer.",
        paidTitle: "This invoice is paid — thank you",
        paidBody: (businessName: string) =>
            `Your payment to ${businessName} is complete. A receipt will follow from the business.`,
        interacStartError: "We couldn't start the Interac payment. Please try again.",
        cardStartError: "We couldn't start the card payment. Please try again.",
    },
    publicBooking: {
        slotsLoadError: "We couldn't load open times. Please try another day.",
        bookError: "We couldn't book that time. It may have just been taken — try another.",
        notFoundTitle: "Booking page not found",
        notFoundBody:
            "This link is invalid or the business isn't accepting online bookings right now.",
        bookWith: "Book an appointment with",
        service: "Service",
        selectService: "Select a service",
        with: "With",
        selectStaff: "Select a team member",
        date: "Date",
        yourName: "Your name",
        fullNamePlaceholder: "Full name",
        email: "Email",
        emailPlaceholder: "you@example.com",
        phone: "Phone",
        phonePlaceholder: "(555) 555-5555",
        reachYouNote: "Add an email or phone so the business can reach you.",
        depositRequired: (amount: string) =>
            `A deposit of ${amount} is required to confirm this booking.`,
        booking: "Booking…",
        confirmBooking: "Confirm booking",
        durationSuffix: (min: number) => ` · ${min} min`,
        anyAvailable: "Any available",
        openTimes: "Open times",
        loadingTimes: "Loading times…",
        noOpenTimes: "No open times that day. Try another date.",
        theDeposit: "the deposit",
        holdSpotTitle: "Hold your spot",
        holdSpotBody: (businessName: string, amount: string) =>
            `Your time with ${businessName} is reserved. Pay the ${amount} deposit to confirm it.`,
        bookedTitle: "You're booked",
        bookedBody: (businessName: string) =>
            `Your appointment with ${businessName} is confirmed. They'll be in touch with any details.`,
        depositLinkNote:
            "A deposit is required to hold this booking — a secure payment link will follow by email or text.",
        incompleteForm: "Add your name and an email or phone, then pick a time.",
        addonsTitle: "Add to your visit",
        addonsNote: "Optional. Paid with your visit, not now.",
        addonsTotal: (amount: string) => `Add-ons: ${amount}, paid at your visit`,
        shopLink: "Shop products",
    },
    publicShop: {
        notFoundTitle: "Shop not found",
        notFoundBody: "This link is invalid or the business isn't selling online right now.",
        title: (business: string) => `Shop ${business}`,
        subtitle: "Pay online and collect your order in person.",
        empty: "Nothing is for sale online right now.",
        outOfStock: "Out of stock",
        quantity: "quantity",
        add: "Add",
        cart: "Your order",
        cartEmpty: "Add something to start an order.",
        subtotal: "Subtotal",
        taxNote: "Tax is added at checkout.",
        yourDetails: "Your details",
        name: "Your name",
        email: "Email",
        phone: "Phone",
        reachYouNote: "Add an email or phone so the business can tell you when it's ready.",
        placeOrder: "Continue to payment",
        placing: "Placing order…",
        payTitle: "Pay for your order",
        total: (amount: string) => `Total ${amount}, tax included`,
        payNow: (amount: string) => `Pay ${amount}`,
        paying: "Paying…",
        back: "Back to your order",
        paidTitle: "Order placed",
        paidBody: (business: string) =>
            `${business} has your order. They'll let you know when it's ready to pick up.`,
        notTakingPayments: "This shop isn't taking online payments right now.",
        incomplete: "Add a product, your name and an email or phone.",
        orderError: "We couldn't place the order. Please try again.",
    },
    navigation: {
        createMenu: "Create",
        newClient: "New client",
        newBooking: "New booking",
        newInvoice: "New invoice",
        newSale: "New sale",
        today: "Today",
        schedule: "Schedule",
        clients: "Clients",
        payments: "Payments",
        inbox: "Inbox",
        setup: "Setup",
        signOut: "Sign out",
        paymentsTabs: {
            invoices: "Invoices",
            sales: "Sales",
            giftCards: "Gift cards",
            staffPay: "Staff pay",
            reports: "Reports",
        },
        setupSections: {
            business: "Business",
            services: "Services & products",
            team: "Team & hours",
            gettingPaid: "Getting paid",
            onlineBooking: "Online booking",
        },
        inboxSegments: {
            messages: "Messages",
            reviews: "Reviews",
        },
    },
    publicContract: {
        sign: "Sign contract",
        signedStatus: "Contract signed",
        declinedStatus: "Contract declined",
        fullNamePlaceholder: "Full legal name",
        signedThanks: (contractName: string, businessName: string) =>
            `Thank you. Your signature on “${contractName}” for ${businessName} is recorded.`,
        declinedNote: (contractName: string, businessName: string) =>
            `You declined “${contractName}”. Contact ${businessName} if this was a mistake.`,
        notFoundTitle: "Contract not found",
        notFoundBody:
            "This signing link is invalid or has expired. Please check with the business that sent it to you.",
        typeNameToSign: "Type your full name to sign",
        uploadSignature: "Or upload a signature image",
        attached: (name: string) => `Attached: ${name}`,
        decline: "Decline",
        esignConsent:
            "By typing your name and signing, you agree this is your electronic signature.",
        signatureUploadFailedDetail: "the signature upload failed",
        signPrompt: "Type your full name or upload a signature image to sign.",
        signError: "We couldn't record your signature. Please try again.",
        signatureUploadError: "We couldn't upload that signature image. Please try again.",
        recordError: "We couldn't record that. Please try again.",
    },
    publicForm: {
        submitting: "Submitting…",
        submit: "Submit",
        notFoundTitle: "Form not found",
        notFoundBody:
            "This link is invalid or has expired. Please check with the business that sent it to you.",
        fileAttached: "File attached ✓",
        selectPlaceholder: "Select…",
        doneTitle: "Thanks — all done",
        doneBody: (businessName: string) => `Your responses have been sent to ${businessName}.`,
        fileUploadFailedDetail: "the file upload failed",
        answerRequired: (label: string) => `“${label}” is required.`,
        fileUploadError: "We couldn't upload that file. Please try again.",
        submitAnswersError: "We couldn't submit your answers. Please try again.",
    },
    publicReview: {
        prompt: (businessName: string) => `How was your experience with ${businessName}?`,
        ratingLabel: "Your rating",
        notePlaceholder: "Add a note (optional)",
        submit: "Submit review",
        submitting: "Submitting…",
        pickRating: "Please pick a rating.",
        submitError: "Couldn't submit your review. Please try again.",
        notFoundTitle: "Review not found",
        notFoundBody:
            "This link is invalid or has expired. Please check with the business that sent it to you.",
        doneTitle: "Thanks for the feedback",
        doneBody: (businessName: string) => `Your review has been shared with ${businessName}.`,
    },
    publicLanding: {
        book: "Book an appointment",
        servicesTitle: "Services",
        notFoundTitle: "Business not found",
        notFoundBody: "This link is invalid or the business is no longer taking bookings here.",
        pageNotFoundTitle: "Page not found",
        pageNotFoundBody: "Check the link the business sent you, or contact them directly.",
    },
    files: {
        uploadFile: "Upload file",
        uploading: "Uploading…",
        viewUploadedFile: "View uploaded file",
        pickerNotWired: "File picker not wired in this build.",
        uploaded: "Uploaded.",
        changeImage: "Change image",
        logo: "Logo",
        uploadLogo: "Upload logo",
        replaceLogo: "Replace logo",
    },
    checkout: {
        payment: "Payment",
        newCard: "Pay with a new card",
        selectSavedMethod: "Select a saved method",
        chooseSavedMethod: "Choose a saved payment method.",
        addMethodFirst: "Add a payment method to the client first.",
        notConfiguredSavedCard: "Card payments aren’t configured. Charge a saved card instead.",
        notConfiguredContact: "Card payments aren't configured. Please contact the business.",
        back: "Back",
        paymentFailed: "Payment failed. Please try again.",
        charging: "Charging…",
        charge: (amount: string) => `Charge ${amount}`,
        pay: (amount: string) => `Pay ${amount}`,
        saveError: "Couldn’t save the card. Please check the details and try again.",
        saveCard: "Save card",
    },
} as const;
