// AUTO-GENERATED by `make gen-sync-schema` from the backend SQLAlchemy models + sync-rules.yaml.
// Do NOT edit by hand — change the models (and infra/powersync/sync-rules.yaml), then regenerate.
// `id` is the implicit text PK; money = integer cents; json/arrays/timestamps stored as text.
import { column, Schema, Table } from "@powersync/common";

const staff = new Table(
    {
        business_id: column.text,
        user_id: column.text,
        role: column.text,
        payee: column.integer,
        rate_type: column.text,
        rate_bps: column.integer,
        rate_cents: column.integer,
        retail_rate_bps: column.integer,
        name: column.text,
        title: column.text,
        color: column.text,
        status: column.text,
        invite_email: column.text,
        invite_token: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            staff_business_id: ["business_id"],
        },
    },
);

const clients = new Table(
    {
        created_by: column.text,
        name: column.text,
        email: column.text,
        phone: column.text,
        user_id: column.text,
        tags: column.text,
        status: column.text,
        custom_fields: column.text,
        stripe_customer_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        deleted_at: column.text,
    },
    {
        indexes: {
            clients_business_email: ["business_id", "email"],
            clients_business_id: ["business_id"],
            clients_business_phone: ["business_id", "phone"],
        },
    },
);

const items = new Table(
    {
        created_by: column.text,
        kind: column.text,
        name: column.text,
        description: column.text,
        price_cents: column.integer,
        currency: column.text,
        duration_min: column.integer,
        capacity: column.integer,
        category: column.text,
        color: column.text,
        online_bookable: column.integer,
        sell_online: column.integer,
        buffer_before_min: column.integer,
        buffer_after_min: column.integer,
        deposit_type: column.text,
        deposit_value: column.real,
        interval: column.integer,
        frequency: column.text,
        session_count: column.integer,
        validity_days: column.integer,
        covers_item_id: column.text,
        visits_per_period: column.integer,
        member_discount_bps: column.integer,
        gift_amounts: column.text,
        stripe_price_id: column.text,
        tax_class: column.text,
        sku: column.text,
        cost_cents: column.integer,
        track_stock: column.integer,
        stock_on_hand: column.integer,
        low_stock_at: column.integer,
        active: column.integer,
        custom_fields: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            items_business_id: ["business_id"],
            items_business_kind_active: ["business_id", "kind", "active"],
            ux_items_business_sku: ["business_id", "sku"],
        },
    },
);

const packages = new Table(
    {
        client_id: column.text,
        item_id: column.text,
        sessions_total: column.integer,
        expires_at: column.text,
        status: column.text,
        payment_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            packages_business_id: ["business_id"],
            packages_client_status: ["business_id", "client_id", "status"],
        },
    },
);

const subscriptions = new Table(
    {
        client_id: column.text,
        item_id: column.text,
        status: column.text,
        current_period_start: column.text,
        current_period_end: column.text,
        payment_method_id: column.text,
        provider_ref: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            subscriptions_active_unique: ["business_id", "client_id", "item_id"],
            subscriptions_business_id: ["business_id"],
            subscriptions_client_status: ["business_id", "client_id", "status"],
            subscriptions_provider_ref: ["provider_ref"],
        },
    },
);

const gift_cards = new Table(
    {
        code: column.text,
        item_id: column.text,
        initial_cents: column.integer,
        purchaser_client_id: column.text,
        recipient: column.text,
        expires_at: column.text,
        status: column.text,
        payment_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            gift_cards_business_id: ["business_id"],
        },
    },
);

const forms = new Table(
    {
        name: column.text,
        attach_to: column.text,
        require_signature: column.integer,
        active: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            forms_business_id: ["business_id"],
        },
    },
);

const fields = new Table(
    {
        form_id: column.text,
        input: column.text,
        name: column.text,
        label: column.text,
        help: column.text,
        required: column.integer,
        options: column.text,
        validation: column.text,
        position: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            fields_business_id: ["business_id"],
            fields_form: ["form_id", "position"],
        },
    },
);

const contracts = new Table(
    {
        name: column.text,
        body: column.text,
        version: column.integer,
        always_require: column.integer,
        active: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            contracts_business_id: ["business_id"],
        },
    },
);

const files = new Table(
    {
        parent_type: column.text,
        parent_id: column.text,
        purpose: column.text,
        s3_key: column.text,
        content_type: column.text,
        size: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            files_business_id: ["business_id"],
            files_parent: ["business_id", "parent_type", "parent_id"],
        },
    },
);

const threads = new Table(
    {
        client_id: column.text,
        channel: column.text,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            threads_business_id: ["business_id"],
        },
    },
);

const messages = new Table(
    {
        thread_id: column.text,
        direction: column.text,
        channel: column.text,
        sent_by: column.text,
        body: column.text,
        status: column.text,
        broadcast_id: column.text,
        provider_ref: column.text,
        attachments: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            messages_broadcast: ["broadcast_id"],
            messages_business_id: ["business_id"],
            messages_thread: ["thread_id", "created_at"],
        },
    },
);

const businesses = new Table(
    {
        name: column.text,
        slug: column.text,
        locale: column.text,
        timezone: column.text,
        province: column.text,
        gst_hst_number: column.text,
        qst_number: column.text,
        tax_registered: column.integer,
        brand: column.text,
        billing_email: column.text,
        stripe_account_id: column.text,
        stripe_terminal_location_id: column.text,
        stripe_charges_enabled: column.integer,
        stripe_payouts_enabled: column.integer,
        stripe_details_submitted: column.integer,
        stripe_requirements: column.text,
        status: column.text,
        staff_discount_limit_bps: column.integer,
        filing_frequency: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            businesses_stripe_account: ["stripe_account_id"],
        },
    },
);

const orders = new Table(
    {
        client_id: column.text,
        staff_id: column.text,
        number: column.integer,
        status: column.text,
        currency: column.text,
        subtotal_cents: column.integer,
        tax_total_cents: column.integer,
        total_cents: column.integer,
        receipt_email: column.text,
        receipt_phone: column.text,
        source: column.text,
        pickup_status: column.text,
        ready_at: column.text,
        picked_up_at: column.text,
        note: column.text,
        approved_by: column.text,
        receipt_token: column.text,
        receipt_channel: column.text,
        receipt_sent_at: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        discount_kind: column.text,
        discount_value: column.integer,
        discount_reason: column.text,
    },
    {
        indexes: {
            orders_business_id: ["business_id"],
            orders_status: ["business_id", "status"],
        },
    },
);

const lines = new Table(
    {
        estimate_id: column.text,
        invoice_id: column.text,
        order_id: column.text,
        description: column.text,
        item_id: column.text,
        booking_id: column.text,
        quantity: column.real,
        unit_amount_cents: column.integer,
        amount_cents: column.integer,
        tax_amount_cents: column.integer,
        tax_class: column.text,
        position: column.integer,
        staff_id: column.text,
        discount_cents: column.integer,
        sale_discount_cents: column.integer,
        for_pickup: column.integer,
        optional: column.integer,
        selected: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        discount_kind: column.text,
        discount_value: column.integer,
        discount_reason: column.text,
    },
    {
        indexes: {
            lines_business_id: ["business_id"],
            lines_estimate: ["estimate_id"],
            lines_invoice: ["invoice_id"],
            lines_order: ["order_id"],
        },
    },
);

const slots = new Table(
    {
        item_id: column.text,
        staff_id: column.text,
        resource_id: column.text,
        recurrence_id: column.text,
        starts_at: column.text,
        ends_at: column.text,
        capacity: column.integer,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            slots_business_id: ["business_id"],
            slots_business_start: ["business_id", "starts_at"],
            slots_staff_start: ["business_id", "staff_id", "starts_at"],
        },
    },
);

const bookings = new Table(
    {
        slot_id: column.text,
        staff_id: column.text,
        client_id: column.text,
        subject_id: column.text,
        package_id: column.text,
        invoice_id: column.text,
        status: column.text,
        source: column.text,
        price_cents: column.integer,
        deposit_amount_cents: column.integer,
        deposit_status: column.text,
        confirmed_at: column.text,
        checked_in_at: column.text,
        order_id: column.text,
        charged_at: column.text,
        completed_at: column.text,
        canceled_at: column.text,
        reminded_at: column.text,
        custom_fields: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        deleted_at: column.text,
    },
    {
        indexes: {
            bookings_business_id: ["business_id"],
            bookings_client: ["business_id", "client_id"],
            bookings_slot: ["business_id", "slot_id"],
            bookings_staff: ["business_id", "staff_id"],
            bookings_status: ["business_id", "status"],
        },
    },
);

const addons = new Table(
    {
        booking_id: column.text,
        staff_id: column.text,
        item_id: column.text,
        description: column.text,
        quantity: column.integer,
        unit_amount_cents: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            addons_booking: ["business_id", "booking_id"],
            addons_business_id: ["business_id"],
        },
    },
);

const hours = new Table(
    {
        staff_id: column.text,
        basis: column.text,
        weekday: column.integer,
        date: column.text,
        start_time: column.text,
        end_time: column.text,
        available: column.integer,
        note: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            hours_business_id: ["business_id"],
            hours_staff: ["business_id", "staff_id", "basis"],
        },
    },
);

const accounts = new Table(
    {
        owner_type: column.text,
        owner_id: column.text,
        category: column.text,
        code: column.text,
        currency: column.text,
        balance_cents: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            accounts_business_id: ["business_id"],
            ux_accounts_identity: [
                "business_id",
                "owner_type",
                "owner_id",
                "category",
                "code",
                "currency",
            ],
        },
    },
);

const entries = new Table(
    {
        journal_id: column.text,
        account_id: column.text,
        owner_type: column.text,
        owner_id: column.text,
        amount_cents: column.integer,
        currency: column.text,
        event: column.text,
        source_type: column.text,
        source_id: column.text,
        subject_type: column.text,
        subject_id: column.text,
        ref: column.text,
        leg: column.integer,
        meta: column.text,
        occurred_at: column.text,
        available_at: column.text,
        created_at: column.text,
        business_id: column.text,
    },
    {
        indexes: {
            entries_account: ["account_id", "occurred_at"],
            entries_business_id: ["business_id"],
            entries_journal: ["journal_id"],
            entries_owner: ["owner_type", "owner_id"],
            entries_source: ["source_type", "source_id"],
            entries_subject: ["subject_type", "subject_id"],
            ux_entries_ref_leg: ["ref", "leg"],
        },
    },
);

const invoices = new Table(
    {
        client_id: column.text,
        number: column.integer,
        status: column.text,
        currency: column.text,
        subtotal_cents: column.integer,
        tax_total_cents: column.integer,
        total_cents: column.integer,
        issued_at: column.text,
        due_at: column.text,
        overdue_notified_at: column.text,
        voided_at: column.text,
        notes: column.text,
        pay_token: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        discount_kind: column.text,
        discount_value: column.integer,
        discount_reason: column.text,
    },
    {
        indexes: {
            invoices_business_id: ["business_id"],
            invoices_client: ["business_id", "client_id"],
            invoices_status: ["business_id", "status"],
        },
    },
);

const estimates = new Table(
    {
        client_id: column.text,
        number: column.integer,
        status: column.text,
        subtotal_cents: column.integer,
        tax_total_cents: column.integer,
        total_cents: column.integer,
        valid_until: column.text,
        accepted_at: column.text,
        declined_at: column.text,
        converted_invoice_id: column.text,
        notes: column.text,
        decline_reason: column.text,
        view_token: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        discount_kind: column.text,
        discount_value: column.integer,
        discount_reason: column.text,
    },
    {
        indexes: {
            estimates_business_id: ["business_id"],
            estimates_status: ["business_id", "status"],
        },
    },
);

const inventory = new Table(
    {
        item_id: column.text,
        line_id: column.text,
        reason: column.text,
        quantity: column.integer,
        unit_cost_cents: column.integer,
        note: column.text,
        created_by: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            inventory_business_id: ["business_id"],
            inventory_item: ["business_id", "item_id"],
            ux_inventory_line_reason: ["line_id", "reason"],
        },
    },
);

const payments = new Table(
    {
        client_id: column.text,
        kind: column.text,
        parent_payment_id: column.text,
        invoice_id: column.text,
        order_id: column.text,
        booking_id: column.text,
        amount_cents: column.integer,
        currency: column.text,
        method: column.text,
        provider: column.text,
        provider_ref: column.text,
        reference_code: column.text,
        reference: column.text,
        note: column.text,
        tendered_cents: column.integer,
        status: column.text,
        paid_at: column.text,
        reason: column.text,
        credit_note: column.text,
        channel: column.text,
        expires_at: column.text,
        dispute_status: column.text,
        dispute_reason: column.text,
        dispute_respond_by: column.text,
        tip_cents: column.integer,
        tip_split: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            payments_business_id: ["business_id"],
            payments_invoice: ["invoice_id"],
            payments_order: ["order_id"],
            payments_provider_ref: ["provider_ref"],
            payments_reference_code: ["reference_code"],
            payments_refund_parent: ["parent_payment_id"],
            payments_status: ["business_id", "status"],
            ux_payments_credit_note: ["business_id", "credit_note"],
        },
    },
);

const payment_methods = new Table(
    {
        client_id: column.text,
        method: column.text,
        brand: column.text,
        last4: column.text,
        provider: column.text,
        provider_ref: column.text,
        preferred: column.integer,
        mandate_status: column.text,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            payment_methods_business_id: ["business_id"],
            payment_methods_client: ["business_id", "client_id"],
            payment_methods_provider: ["business_id", "provider_ref"],
        },
    },
);

const reviews = new Table(
    {
        client_id: column.text,
        booking_id: column.text,
        channel: column.text,
        token: column.text,
        status: column.text,
        requested_at: column.text,
        submitted_at: column.text,
        rating: column.integer,
        body: column.text,
        response: column.text,
        responded_at: column.text,
        sent_to_google: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            reviews_business_id: ["business_id"],
            reviews_status_created: ["business_id", "status", "created_at"],
            uq_reviews_open_booking: ["business_id", "booking_id"],
        },
    },
);

const device_prefs = new Table(
    {
        value: column.text,
        updated_at: column.text,
    },
    { localOnly: true },
);

export const AppSchema = new Schema({
    staff,
    clients,
    items,
    packages,
    subscriptions,
    gift_cards,
    forms,
    fields,
    contracts,
    files,
    threads,
    messages,
    businesses,
    orders,
    lines,
    slots,
    bookings,
    addons,
    hours,
    accounts,
    entries,
    invoices,
    estimates,
    inventory,
    payments,
    payment_methods,
    reviews,
    device_prefs,
});

export type Database = (typeof AppSchema)["types"];
