// AUTO-GENERATED by `make gen-sync-schema` from the backend SQLAlchemy models + sync-rules.yaml.
// Do NOT edit by hand — change the models (and infra/powersync/sync-rules.yaml), then regenerate.
// `id` is the implicit text PK; money = integer cents; json/arrays/timestamps stored as text.
import { column, Schema, Table } from "@powersync/common";

const staff = new Table(
    {
        business_id: column.text,
        user_id: column.text,
        role: column.text,
        is_payee: column.integer,
        payout_ref: column.text,
        default_rate: column.real,
        rate_type: column.text,
        title: column.text,
        color: column.text,
        status: column.text,
        invite_email: column.text,
        invite_token: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            staff_business_id: ["business_id"],
        },
    },
);

const businesses = new Table(
    {
        name: column.text,
        slug: column.text,
        parent_business_id: column.text,
        locale: column.text,
        timezone: column.text,
        province: column.text,
        gst_hst_number: column.text,
        qst_number: column.text,
        is_tax_registered: column.integer,
        brand: column.text,
        plan: column.text,
        billing_email: column.text,
        stripe_customer_id: column.text,
        stripe_account_id: column.text,
        stripe_terminal_location_id: column.text,
        stripe_charges_enabled: column.integer,
        stripe_payouts_enabled: column.integer,
        stripe_details_submitted: column.integer,
        stripe_requirements: column.text,
        kyc_status: column.text,
        payout_schedule: column.text,
        status: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            businesses_stripe_account: ["stripe_account_id"],
        },
    },
);

const clients = new Table(
    {
        created_by: column.text,
        name: column.text,
        email: column.text,
        phone: column.text,
        user_id: column.text,
        tags: column.text,
        status: column.text,
        lifetime_value_cents: column.integer,
        custom_fields: column.text,
        stripe_customer_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        deleted_at: column.text,
    },
    {
        indexes: {
            clients_business_email: ["business_id", "email"],
            clients_business_id: ["business_id"],
            clients_business_phone: ["business_id", "phone"],
        },
    },
);

const subjects = new Table(
    {
        client_id: column.text,
        kind: column.text,
        name: column.text,
        attributes: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            subjects_business_client: ["business_id", "client_id"],
            subjects_business_id: ["business_id"],
        },
    },
);

const notes = new Table(
    {
        author_user_id: column.text,
        parent_type: column.text,
        parent_id: column.text,
        body: column.text,
        pinned: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            notes_business_id: ["business_id"],
            notes_parent: ["business_id", "parent_type", "parent_id"],
        },
    },
);

const items = new Table(
    {
        created_by: column.text,
        kind: column.text,
        name: column.text,
        description: column.text,
        price_cents: column.integer,
        currency: column.text,
        duration_min: column.integer,
        capacity: column.integer,
        category: column.text,
        color: column.text,
        online_bookable: column.integer,
        buffer_before_min: column.integer,
        buffer_after_min: column.integer,
        deposit_type: column.text,
        deposit_value: column.real,
        interval: column.integer,
        frequency: column.text,
        session_count: column.integer,
        validity_days: column.integer,
        pack: column.text,
        stripe_price_id: column.text,
        active: column.integer,
        custom_fields: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            items_business_id: ["business_id"],
            items_business_kind_active: ["business_id", "kind", "active"],
        },
    },
);

const packages = new Table(
    {
        client_id: column.text,
        item_id: column.text,
        sessions_total: column.integer,
        sessions_used: column.integer,
        expires_at: column.text,
        status: column.text,
        payment_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            packages_business_id: ["business_id"],
            packages_client_status: ["business_id", "client_id", "status"],
        },
    },
);

const subscriptions = new Table(
    {
        client_id: column.text,
        item_id: column.text,
        status: column.text,
        current_period_start: column.text,
        current_period_end: column.text,
        payment_method_id: column.text,
        provider_ref: column.text,
        trial_end_at: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            subscriptions_active_unique: ["business_id", "client_id", "item_id"],
            subscriptions_business_id: ["business_id"],
            subscriptions_client_status: ["business_id", "client_id", "status"],
            subscriptions_provider_ref: ["provider_ref"],
        },
    },
);

const gift_cards = new Table(
    {
        code: column.text,
        item_id: column.text,
        initial_cents: column.integer,
        balance_cents: column.integer,
        purchaser_client_id: column.text,
        recipient: column.text,
        expires_at: column.text,
        status: column.text,
        payment_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            gift_cards_business_id: ["business_id"],
        },
    },
);

const resources = new Table(
    {
        name: column.text,
        kind: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            resources_business_id: ["business_id"],
        },
    },
);

const forms = new Table(
    {
        name: column.text,
        attach_to: column.text,
        require_signature: column.integer,
        active: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            forms_business_id: ["business_id"],
        },
    },
);

const form_fields = new Table(
    {
        form_id: column.text,
        type: column.text,
        name: column.text,
        label: column.text,
        help: column.text,
        required: column.integer,
        options: column.text,
        validation: column.text,
        default: column.text,
        position: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            form_fields_business_id: ["business_id"],
            form_fields_form: ["form_id", "position"],
        },
    },
);

const form_responses = new Table(
    {
        form_id: column.text,
        client_id: column.text,
        parent_type: column.text,
        parent_id: column.text,
        token: column.text,
        status: column.text,
        submitted_at: column.text,
        answers: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            form_responses_business_id: ["business_id"],
            form_responses_form: ["business_id", "form_id"],
            form_responses_parent: ["parent_type", "parent_id"],
        },
    },
);

const contracts = new Table(
    {
        name: column.text,
        body: column.text,
        version: column.integer,
        always_require: column.integer,
        expires: column.text,
        active: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            contracts_business_id: ["business_id"],
        },
    },
);

const signatures = new Table(
    {
        contract_id: column.text,
        client_id: column.text,
        parent_type: column.text,
        parent_id: column.text,
        token: column.text,
        signed_at: column.text,
        signature_image_id: column.text,
        signed_body: column.text,
        ip: column.text,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            signatures_business_id: ["business_id"],
            signatures_contract: ["business_id", "contract_id"],
            signatures_parent: ["parent_type", "parent_id"],
        },
    },
);

const files = new Table(
    {
        parent_type: column.text,
        parent_id: column.text,
        kind: column.text,
        s3_key: column.text,
        content_type: column.text,
        size: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            files_business_id: ["business_id"],
            files_parent: ["business_id", "parent_type", "parent_id"],
        },
    },
);

const threads = new Table(
    {
        client_id: column.text,
        channel: column.text,
        last_message_at: column.text,
        unread_count: column.integer,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            threads_business_id: ["business_id"],
            threads_last_message: ["business_id", "last_message_at"],
        },
    },
);

const messages = new Table(
    {
        thread_id: column.text,
        direction: column.text,
        channel: column.text,
        sender_user_id: column.text,
        body: column.text,
        status: column.text,
        broadcast_id: column.text,
        provider_ref: column.text,
        attachments: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            messages_broadcast: ["broadcast_id"],
            messages_business_id: ["business_id"],
            messages_thread: ["thread_id", "created_at"],
        },
    },
);

const broadcasts = new Table(
    {
        created_by: column.text,
        name: column.text,
        channel: column.text,
        body: column.text,
        audience: column.text,
        status: column.text,
        scheduled_at: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            broadcasts_business_id: ["business_id"],
            broadcasts_status: ["business_id", "status"],
        },
    },
);

const sessions = new Table(
    {
        item_id: column.text,
        staff_id: column.text,
        resource_id: column.text,
        recurrence_id: column.text,
        starts_at: column.text,
        ends_at: column.text,
        capacity: column.integer,
        booked_count: column.integer,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            sessions_business_id: ["business_id"],
            sessions_business_start: ["business_id", "starts_at"],
            sessions_staff_start: ["business_id", "staff_id", "starts_at"],
        },
    },
);

const bookings = new Table(
    {
        session_id: column.text,
        staff_id: column.text,
        client_id: column.text,
        subject_id: column.text,
        package_id: column.text,
        invoice_id: column.text,
        status: column.text,
        source: column.text,
        price_cents: column.integer,
        deposit_required: column.integer,
        deposit_amount_cents: column.integer,
        deposit_status: column.text,
        confirmed_at: column.text,
        completed_at: column.text,
        canceled_at: column.text,
        reminded_at: column.text,
        custom_fields: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
        deleted_at: column.text,
    },
    {
        indexes: {
            bookings_business_id: ["business_id"],
            bookings_client: ["business_id", "client_id"],
            bookings_session: ["business_id", "session_id"],
            bookings_staff: ["business_id", "staff_id"],
            bookings_status: ["business_id", "status"],
        },
    },
);

const availability = new Table(
    {
        staff_id: column.text,
        type: column.text,
        weekday: column.integer,
        date: column.text,
        start_time: column.text,
        end_time: column.text,
        is_available: column.integer,
        note: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            availability_business_id: ["business_id"],
            availability_staff: ["business_id", "staff_id", "type"],
        },
    },
);

const schedules = new Table(
    {
        item_id: column.text,
        staff_id: column.text,
        client_id: column.text,
        frequency: column.text,
        interval: column.integer,
        byday: column.text,
        count: column.integer,
        until: column.text,
        start_date: column.text,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            schedules_business_id: ["business_id"],
            schedules_status: ["business_id", "status"],
        },
    },
);

const payout_allocations = new Table(
    {
        staff_id: column.text,
        source_type: column.text,
        source_id: column.text,
        basis: column.text,
        rate: column.real,
        amount_cents: column.integer,
        status: column.text,
        payout_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            payout_alloc_source: ["source_type", "source_id", "staff_id"],
            payout_alloc_staff: ["business_id", "staff_id", "status"],
            payout_allocations_business_id: ["business_id"],
        },
    },
);

const invoices = new Table(
    {
        client_id: column.text,
        number: column.integer,
        status: column.text,
        currency: column.text,
        subtotal_cents: column.integer,
        tax_total_cents: column.integer,
        total_cents: column.integer,
        amount_paid_cents: column.integer,
        balance_cents: column.integer,
        issued_at: column.text,
        due_at: column.text,
        paid_at: column.text,
        voided_at: column.text,
        notes: column.text,
        pay_token: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            invoices_business_id: ["business_id"],
            invoices_client: ["business_id", "client_id"],
            invoices_status: ["business_id", "status"],
        },
    },
);

const estimates = new Table(
    {
        client_id: column.text,
        number: column.integer,
        status: column.text,
        subtotal_cents: column.integer,
        tax_total_cents: column.integer,
        total_cents: column.integer,
        valid_until: column.text,
        accepted_at: column.text,
        declined_at: column.text,
        converted_invoice_id: column.text,
        notes: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            estimates_business_id: ["business_id"],
            estimates_status: ["business_id", "status"],
        },
    },
);

const orders = new Table(
    {
        client_id: column.text,
        staff_id: column.text,
        status: column.text,
        currency: column.text,
        subtotal_cents: column.integer,
        tax_total_cents: column.integer,
        total_cents: column.integer,
        amount_paid_cents: column.integer,
        balance_cents: column.integer,
        paid_at: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            orders_business_id: ["business_id"],
            orders_status: ["business_id", "status"],
        },
    },
);

const lines = new Table(
    {
        parent_type: column.text,
        parent_id: column.text,
        description: column.text,
        item_id: column.text,
        booking_id: column.text,
        quantity: column.real,
        unit_amount_cents: column.integer,
        amount_cents: column.integer,
        tax_amount_cents: column.integer,
        position: column.integer,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            lines_business_id: ["business_id"],
            lines_parent: ["parent_type", "parent_id"],
        },
    },
);

const payments = new Table(
    {
        client_id: column.text,
        kind: column.text,
        parent_payment_id: column.text,
        invoice_id: column.text,
        order_id: column.text,
        booking_id: column.text,
        amount_cents: column.integer,
        currency: column.text,
        method: column.text,
        provider: column.text,
        provider_ref: column.text,
        reference_code: column.text,
        fee_cents: column.integer,
        net_cents: column.integer,
        status: column.text,
        paid_at: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            payments_business_id: ["business_id"],
            payments_invoice: ["invoice_id"],
            payments_order: ["order_id"],
            payments_provider_ref: ["provider_ref"],
            payments_reference_code: ["reference_code"],
            payments_refund_parent: ["parent_payment_id"],
            payments_status: ["business_id", "status"],
        },
    },
);

const payment_methods = new Table(
    {
        client_id: column.text,
        type: column.text,
        brand: column.text,
        last4: column.text,
        provider: column.text,
        provider_ref: column.text,
        is_default: column.integer,
        mandate_status: column.text,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            payment_methods_business_id: ["business_id"],
            payment_methods_client: ["business_id", "client_id"],
            payment_methods_provider: ["business_id", "provider_ref"],
        },
    },
);

const payouts = new Table(
    {
        amount_cents: column.integer,
        status: column.text,
        arrival_at: column.text,
        provider_ref: column.text,
        bank_last4: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            payouts_business_id: ["business_id"],
            payouts_provider_ref: ["business_id", "provider_ref"],
            payouts_status: ["business_id", "status"],
        },
    },
);

const reviews = new Table(
    {
        client_id: column.text,
        booking_id: column.text,
        rating: column.integer,
        body: column.text,
        response: column.text,
        responded_at: column.text,
        sent_to_google: column.integer,
        status: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            reviews_business_id: ["business_id"],
            reviews_status_created: ["business_id", "status", "created_at"],
        },
    },
);

const review_requests = new Table(
    {
        client_id: column.text,
        booking_id: column.text,
        channel: column.text,
        token: column.text,
        status: column.text,
        sent_at: column.text,
        reminder_count: column.integer,
        review_id: column.text,
        business_id: column.text,
        created_at: column.text,
        updated_at: column.text,
    },
    {
        indexes: {
            review_requests_business_id: ["business_id"],
            review_requests_status: ["business_id", "status"],
            uq_review_requests_open_booking: ["business_id", "booking_id"],
        },
    },
);

const audit_logs = new Table(
    {
        actor_user_id: column.text,
        action: column.text,
        entity_type: column.text,
        entity_id: column.text,
        changes: column.text,
        created_at: column.text,
        business_id: column.text,
    },
    {
        indexes: {
            audit_created: ["business_id", "created_at"],
            audit_entity: ["business_id", "entity_type", "entity_id"],
            audit_logs_business_id: ["business_id"],
        },
    },
);

export const AppSchema = new Schema({
    staff,
    businesses,
    clients,
    subjects,
    notes,
    items,
    packages,
    subscriptions,
    gift_cards,
    resources,
    forms,
    form_fields,
    form_responses,
    contracts,
    signatures,
    files,
    threads,
    messages,
    broadcasts,
    sessions,
    bookings,
    availability,
    schedules,
    payout_allocations,
    invoices,
    estimates,
    orders,
    lines,
    payments,
    payment_methods,
    payouts,
    reviews,
    review_requests,
    audit_logs,
});

export type Database = (typeof AppSchema)["types"];
