// Shared flat config: strictTypeChecked bans `any` and unsafe-any data flows.
import js from "@eslint/js";
import tseslint from "typescript-eslint";

import noInlineUiString from "./no-inline-ui-string.mjs";

export default tseslint.config(
    js.configs.recommended,
    ...tseslint.configs.strictTypeChecked,
    ...tseslint.configs.stylisticTypeChecked,
    {
        plugins: { local: { rules: { "no-inline-ui-string": noInlineUiString } } },
        rules: {
            "no-console": "error",
            // Ban `void`; ignoreVoid:false so a floating promise needs a real .catch/await, not void.
            "no-void": "error",
            "@typescript-eslint/no-floating-promises": ["error", { ignoreVoid: false }],
            "@typescript-eslint/no-explicit-any": "error",
            // Numbers in template strings are fine; objects and any are still banned.
            "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
            // `allow` lists brand tokens that are legitimately inline, not catalog copy.
            "local/no-inline-ui-string": ["error", { allow: ["Clientbridge", "PowerSync"] }],
        },
    },
    {
        // Debug overlays are dev tooling, not product copy.
        files: ["**/Debug*.tsx"],
        rules: { "local/no-inline-ui-string": "off" },
    },
    {
        // Connect and app-core/public must never pull the PowerSync replica stack into the customer bundle.
        files: [
            "**/apps/connect/src/**/*.{ts,tsx}",
            "**/packages/app-core/src/public.ts",
            "**/packages/app-core/src/domain/public*.ts",
        ],
        rules: {
            "@typescript-eslint/no-restricted-imports": [
                "error",
                {
                    patterns: [
                        {
                            group: ["@powersync/*", "@clientbridge/sync"],
                            message:
                                "PowerSync must not reach the Connect bundle — keep this file on the app-core/public (PowerSync-free) surface.",
                        },
                    ],
                },
            ],
        },
    },
    {
        // Web UI is used by Connect too, so it stays on the PowerSync-free surface and off React Native.
        files: ["**/packages/ui/src/web/**/*.{ts,tsx}"],
        rules: {
            "@typescript-eslint/no-restricted-imports": [
                "error",
                {
                    paths: [
                        {
                            name: "@clientbridge/app-core",
                            message: "Import from @clientbridge/app-core/public in shared UI.",
                        },
                    ],
                    patterns: [
                        { group: ["@powersync/*", "@clientbridge/sync"] },
                        {
                            group: [
                                "react-native",
                                "react-native-*",
                                "@stripe/stripe-react-native",
                            ],
                            message: "React Native belongs in packages/ui/src/mobile.",
                        },
                    ],
                },
            ],
        },
    },
    {
        files: ["**/packages/ui/src/mobile/**/*.{ts,tsx}"],
        rules: {
            "@typescript-eslint/no-restricted-imports": [
                "error",
                {
                    patterns: [
                        { group: ["@powersync/*", "@clientbridge/sync"] },
                        {
                            group: [
                                "react-dom",
                                "react-dom/*",
                                "@stripe/stripe-js",
                                "@stripe/react-stripe-js",
                            ],
                            message: "DOM code belongs in packages/ui/src/web.",
                        },
                    ],
                },
            ],
        },
    },
    {
        ignores: [
            "**/dist/**",
            "**/public/**", // static assets served as-is (e.g. the vanilla embed loader)
            "node_modules/**",
            "**/generated/**",
            "**/generated.ts", // the openapi-typescript output (packages/api-client/src/generated.ts)
            "**/*.cjs", // CommonJS build/codegen scripts (repo is ESM); not type-lintable
            "**/*.config.{js,ts,mjs,cjs}",
            "**/packages/config/**/*.mjs", // flat config, lint rules and the structure check: tooling, in no tsconfig
            "**/apps/mobile/{ios,android}/**", // native projects generated by `expo prebuild`
            "**/.expo/**",
        ],
    },
);
