// AUTO-GENERATED from .docs/design/app-explorer.html — do not edit by hand.

export const THEME_KEYS = ["pewter", "slate", "calm", "fjord", "birch", "moss"] as const;
export type ThemeKey = (typeof THEME_KEYS)[number];

export const THEME_LABELS: Record<ThemeKey, string> = {
    pewter: "Pewter",
    slate: "Slate",
    calm: "Calm",
    fjord: "Fjord",
    birch: "Birch",
    moss: "Moss",
};

export const themes = {
    pewter: {
        color: {
            bg: "#F3F4F6",
            surface: "#FFFFFF",
            surface2: "#EAECEF",
            head: "#F2F3F5",
            ink: "#191D22",
            inkSoft: "#3E454D",
            muted: "#6E757E",
            border: "#DBDEE3",
            borderSoft: "#E8EAEE",
            primary: "#3A4654",
            primaryInk: "#F2F4F6",
            accent: "#3F5E80",
            accentInk: "#FFFFFF",
            accentStrong: "#2E4A66",
            accentWeak: "#E4EAF1",
            accentLine: "#CCD7E3",
            success: "#2E7A5A",
            okBg: "#DEEDE5",
            okFg: "#256048",
            warnBg: "#F3E8CC",
            warnFg: "#86621E",
            danBg: "#F1DFDC",
            danFg: "#A2433A",
            side: "#22282F",
            sideInk: "#99A2AC",
            logo: "#8FB4E0",
        },
        font: {
            ui: "Schibsted Grotesk",
            display: "Schibsted Grotesk",
            mono: "Geist Mono",
        },
        radius: {
            base: 8,
            avatar: 7,
        },
        borderWidth: 1.5,
        shadow: "0 1px 2px rgba(20,25,30,.05)",
    },
    slate: {
        color: {
            bg: "#F4F6F7",
            surface: "#FFFFFF",
            surface2: "#EBEEF0",
            head: "#F2F5F6",
            ink: "#161B1F",
            inkSoft: "#3E454B",
            muted: "#6E767D",
            border: "#E0E4E7",
            borderSoft: "#EBEEF0",
            primary: "#1C2429",
            primaryInk: "#F2F5F6",
            accent: "#0E8A63",
            accentInk: "#FFFFFF",
            accentStrong: "#0B6E4F",
            accentWeak: "#DCF1E8",
            accentLine: "#BCE3D4",
            success: "#0E8A63",
            okBg: "#DCF1E8",
            okFg: "#0B6E4F",
            warnBg: "#F6E8CC",
            warnFg: "#8A6420",
            danBg: "#F4DEDA",
            danFg: "#A8442F",
            side: "#181E22",
            sideInk: "#9AA4AB",
            logo: "#2FC48E",
        },
        font: {
            ui: "Albert Sans",
            display: "Albert Sans",
            mono: "Geist Mono",
        },
        radius: {
            base: 10,
            avatar: 8,
        },
        borderWidth: 1.5,
        shadow: "0 2px 12px rgba(22,27,31,.06)",
    },
    calm: {
        color: {
            bg: "#FBFAF6",
            surface: "#FFFFFF",
            surface2: "#F4F1EA",
            head: "#F8F5EC",
            ink: "#15201D",
            inkSoft: "#3A4843",
            muted: "#6B7B75",
            border: "#E7E2D8",
            borderSoft: "#F0ECE0",
            primary: "#0E3D36",
            primaryInk: "#F4F1EA",
            accent: "#EFA23D",
            accentInk: "#0B2E29",
            accentStrong: "#B26A12",
            accentWeak: "#FCEBCF",
            accentLine: "#F3D9A8",
            success: "#1F9D6B",
            okBg: "#DDF3E9",
            okFg: "#157A52",
            warnBg: "#FCEBCF",
            warnFg: "#8A510C",
            danBg: "#F8E0DB",
            danFg: "#A33A28",
            side: "#0B2E29",
            sideInk: "#9FBDB5",
            logo: "#EFA23D",
        },
        font: {
            ui: "Hanken Grotesk",
            display: "Fraunces",
            mono: "DM Mono",
        },
        radius: {
            base: 15,
            avatar: 999,
        },
        borderWidth: 1.5,
        shadow: "0 2px 14px rgba(11,46,41,.05)",
    },
    fjord: {
        color: {
            bg: "#F3F6F7",
            surface: "#FFFFFF",
            surface2: "#E8EFF1",
            head: "#F0F5F6",
            ink: "#142226",
            inkSoft: "#374B50",
            muted: "#67797E",
            border: "#DCE6E8",
            borderSoft: "#E9F0F1",
            primary: "#123C44",
            primaryInk: "#EEF6F6",
            accent: "#0E7C8A",
            accentInk: "#FFFFFF",
            accentStrong: "#0B5E69",
            accentWeak: "#DAEEF0",
            accentLine: "#BBE0E4",
            success: "#0E8A6E",
            okBg: "#DAEEE8",
            okFg: "#0B6E58",
            warnBg: "#F4E8CC",
            warnFg: "#8A6420",
            danBg: "#F2DFDA",
            danFg: "#A8472F",
            side: "#0E3138",
            sideInk: "#8FB7BC",
            logo: "#48C7D2",
        },
        font: {
            ui: "Onest",
            display: "Onest",
            mono: "Geist Mono",
        },
        radius: {
            base: 12,
            avatar: 9,
        },
        borderWidth: 1.5,
        shadow: "0 2px 12px rgba(14,60,68,.06)",
    },
    birch: {
        color: {
            bg: "#F8F5EF",
            surface: "#FFFFFF",
            surface2: "#F0EBE1",
            head: "#F5F0E7",
            ink: "#221E18",
            inkSoft: "#494238",
            muted: "#7E7568",
            border: "#E7E0D2",
            borderSoft: "#F1ECE1",
            primary: "#2E2A23",
            primaryInk: "#F4F1EA",
            accent: "#B5742B",
            accentInk: "#FFFFFF",
            accentStrong: "#8E5A1E",
            accentWeak: "#F4E8CF",
            accentLine: "#E8D5AC",
            success: "#3E7A4E",
            okBg: "#E2EDDC",
            okFg: "#356345",
            warnBg: "#F5E7CB",
            warnFg: "#8A6420",
            danBg: "#F3DED4",
            danFg: "#A4492C",
            side: "#2A241C",
            sideInk: "#BBB0A0",
            logo: "#E8A84E",
        },
        font: {
            ui: "Figtree",
            display: "Figtree",
            mono: "DM Mono",
        },
        radius: {
            base: 13,
            avatar: 999,
        },
        borderWidth: 1.5,
        shadow: "0 2px 14px rgba(50,40,25,.06)",
    },
    moss: {
        color: {
            bg: "#F4F6F2",
            surface: "#FFFFFF",
            surface2: "#E9EEE3",
            head: "#F1F5ED",
            ink: "#1B231A",
            inkSoft: "#3F4A3A",
            muted: "#6E776A",
            border: "#E0E5D8",
            borderSoft: "#ECF0E6",
            primary: "#34452C",
            primaryInk: "#F0F4EA",
            accent: "#4A6B45",
            accentInk: "#FFFFFF",
            accentStrong: "#395536",
            accentWeak: "#E2EDDC",
            accentLine: "#C7DABF",
            success: "#3E8A52",
            okBg: "#E0EEDD",
            okFg: "#336540",
            warnBg: "#F4E8CC",
            warnFg: "#86621E",
            danBg: "#F1DFDB",
            danFg: "#A2473A",
            side: "#27331F",
            sideInk: "#AABBA0",
            logo: "#86C77A",
        },
        font: {
            ui: "Albert Sans",
            display: "Albert Sans",
            mono: "Geist Mono",
        },
        radius: {
            base: 10,
            avatar: 8,
        },
        borderWidth: 1.5,
        shadow: "0 2px 12px rgba(30,40,25,.06)",
    },
} as const;

export type ThemeTokens = (typeof themes)["pewter"];
