"""initial

Revision ID: 91b9de21ac13
Revises:
Create Date: 2026-06-24 22:54:10.394153
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "91b9de21ac13"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("parent_business_id", sa.String(), nullable=True),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("province", sa.String(), nullable=True),
        sa.Column("gst_hst_number", sa.String(), nullable=True),
        sa.Column("qst_number", sa.String(), nullable=True),
        sa.Column("is_tax_registered", sa.Boolean(), nullable=False),
        sa.Column("brand", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan", sa.String(), nullable=True),
        sa.Column("billing_email", sa.String(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_account_id", sa.String(), nullable=True),
        sa.Column("payout_schedule", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("oauth", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('stripe', 'interac', 'twilio', 'sendgrid')",
            name="ck_webhook_events_provider",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processed', 'failed')", name="ck_webhook_events_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_webhook_provider_status", "webhook_events", ["provider", "status"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_created", "audit_logs", ["business_id", "created_at"], unique=False)
    op.create_index(
        "ix_audit_entity", "audit_logs", ["business_id", "entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_business_id"), "audit_logs", ["business_id"], unique=False)
    op.create_table(
        "broadcasts",
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("audience", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('sms', 'email')", name="ck_broadcasts_channel"),
        sa.CheckConstraint(
            "status IN ('draft', 'scheduled', 'sending', 'sent', 'canceled')",
            name="ck_broadcasts_status",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broadcasts_business_id"), "broadcasts", ["business_id"], unique=False)
    op.create_index("ix_broadcasts_status", "broadcasts", ["business_id", "status"], unique=False)
    op.create_table(
        "clients",
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("lifetime_value_cents", sa.BigInteger(), nullable=False),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_clients_business_email", "clients", ["business_id", "email"], unique=False)
    op.create_index(op.f("ix_clients_business_id"), "clients", ["business_id"], unique=False)
    op.create_index("ix_clients_business_phone", "clients", ["business_id", "phone"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("always_require", sa.Boolean(), nullable=False),
        sa.Column("expires", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contracts_business_id"), "contracts", ["business_id"], unique=False)
    op.create_table(
        "files",
        sa.Column("parent_type", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_business_id"), "files", ["business_id"], unique=False)
    op.create_index(
        "ix_files_parent", "files", ["business_id", "parent_type", "parent_id"], unique=False
    )
    op.create_table(
        "forms",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("attach_to", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("require_signature", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_forms_business_id"), "forms", ["business_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("author_user_id", sa.String(), nullable=True),
        sa.Column("parent_type", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_business_id"), "notes", ["business_id"], unique=False)
    op.create_index(
        "ix_notes_parent", "notes", ["business_id", "parent_type", "parent_id"], unique=False
    )
    op.create_table(
        "payouts",
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("arrival_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_ref", sa.String(), nullable=True),
        sa.Column("bank_last4", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'in_transit', 'paid', 'failed', 'canceled')",
            name="ck_payouts_status",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payouts_business_id"), "payouts", ["business_id"], unique=False)
    op.create_index("ix_payouts_status", "payouts", ["business_id", "status"], unique=False)
    op.create_table(
        "resources",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('room', 'equipment')", name="ck_resources_kind"),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resources_business_id"), "resources", ["business_id"], unique=False)
    op.create_table(
        "staff",
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_payee", sa.Boolean(), nullable=False),
        sa.Column("payout_ref", sa.String(), nullable=True),
        sa.Column("default_rate", sa.Float(), nullable=True),
        sa.Column("rate_type", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("invite_email", sa.String(), nullable=True),
        sa.Column("invite_token", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_staff_business_id"), "staff", ["business_id"], unique=False)
    op.create_table(
        "tax_rates",
        sa.Column("business_id", sa.String(), nullable=True),
        sa.Column("jurisdiction", sa.String(), nullable=False),
        sa.Column("province", sa.String(), nullable=False),
        sa.Column("rate_bps", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jurisdiction IN ('GST', 'HST', 'PST', 'QST')", name="ck_tax_rates_jurisdiction"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tax_rates_business_id"), "tax_rates", ["business_id"], unique=False)
    op.create_index(
        "ix_tax_rates_province", "tax_rates", ["province", "jurisdiction"], unique=False
    )
    op.create_table(
        "availability",
        sa.Column("staff_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("type IN ('recurring', 'date')", name="ck_availability_type"),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_availability_business_id"), "availability", ["business_id"], unique=False
    )
    op.create_index(
        "ix_availability_staff", "availability", ["business_id", "staff_id", "type"], unique=False
    )
    op.create_table(
        "form_fields",
        sa.Column("form_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("help", sa.String(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("default", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('text', 'longtext', 'number', 'currency', 'select', 'multiselect', 'checkbox', 'date', 'time', 'email', 'phone', 'address', 'file', 'image', 'signature', 'rating')",
            name="ck_form_fields_type",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_fields_business_id"), "form_fields", ["business_id"], unique=False
    )
    op.create_index("ix_form_fields_form", "form_fields", ["form_id", "position"], unique=False)
    op.create_table(
        "form_responses",
        sa.Column("form_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("parent_type", sa.String(), nullable=True),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('draft', 'submitted')", name="ck_form_responses_status"),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_responses_business_id"), "form_responses", ["business_id"], unique=False
    )
    op.create_index(
        "ix_form_responses_form", "form_responses", ["business_id", "form_id"], unique=False
    )
    op.create_index(
        "ix_form_responses_parent", "form_responses", ["parent_type", "parent_id"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal_cents", sa.BigInteger(), nullable=False),
        sa.Column("tax_total_cents", sa.BigInteger(), nullable=False),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column("amount_paid_cents", sa.BigInteger(), nullable=False),
        sa.Column("balance_cents", sa.BigInteger(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'partial', 'paid', 'overdue', 'void')",
            name="ck_invoices_status",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "number", name="uq_invoices_business_number"),
    )
    op.create_index(op.f("ix_invoices_business_id"), "invoices", ["business_id"], unique=False)
    op.create_index("ix_invoices_client", "invoices", ["business_id", "client_id"], unique=False)
    op.create_index("ix_invoices_status", "invoices", ["business_id", "status"], unique=False)
    op.create_table(
        "items",
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("tax_rate_id", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("online_bookable", sa.Boolean(), nullable=False),
        sa.Column("buffer_before_min", sa.Integer(), nullable=False),
        sa.Column("buffer_after_min", sa.Integer(), nullable=False),
        sa.Column("deposit_type", sa.String(), nullable=False),
        sa.Column("deposit_value", sa.Numeric(), nullable=True),
        sa.Column("interval", sa.Integer(), nullable=True),
        sa.Column("frequency", sa.String(), nullable=True),
        sa.Column("session_count", sa.Integer(), nullable=True),
        sa.Column("validity_days", sa.Integer(), nullable=True),
        sa.Column("pack", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "deposit_type IN ('none', 'fixed', 'percent')", name="ck_items_deposit_type"
        ),
        sa.CheckConstraint(
            "kind IN ('service', 'class', 'product', 'package', 'subscription', 'gift')",
            name="ck_items_kind",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_rate_id"],
            ["tax_rates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_business_id"), "items", ["business_id"], unique=False)
    op.create_index(
        "ix_items_business_kind_active", "items", ["business_id", "kind", "active"], unique=False
    )
    op.create_table(
        "payment_methods",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("last4", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("provider_ref", sa.String(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("mandate_status", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mandate_status IN ('none', 'pending', 'active', 'revoked')",
            name="ck_payment_methods_mandate_status",
        ),
        sa.CheckConstraint(
            "type IN ('card', 'bank_eft', 'interac')", name="ck_payment_methods_type"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_methods_business_id"), "payment_methods", ["business_id"], unique=False
    )
    op.create_index(
        "ix_payment_methods_client", "payment_methods", ["business_id", "client_id"], unique=False
    )
    op.create_table(
        "payout_allocations",
        sa.Column("staff_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("basis", sa.String(), nullable=True),
        sa.Column("rate", sa.Numeric(), nullable=True),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payout_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "basis IN ('rate', 'percent', 'fixed')", name="ck_payout_allocations_basis"
        ),
        sa.CheckConstraint(
            "source_type IN ('booking', 'invoice_line', 'class_session', 'tip', 'sale')",
            name="ck_payout_allocations_source_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'paid')", name="ck_payout_allocations_status"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["payouts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payout_alloc_source", "payout_allocations", ["source_type", "source_id"], unique=False
    )
    op.create_index(
        "ix_payout_alloc_staff",
        "payout_allocations",
        ["business_id", "staff_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payout_allocations_business_id"),
        "payout_allocations",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "signatures",
        sa.Column("contract_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("parent_type", sa.String(), nullable=True),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signature_image_id", sa.String(), nullable=True),
        sa.Column("signed_body", sa.String(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'signed', 'declined', 'expired')", name="ck_signatures_status"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signature_image_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signatures_business_id"), "signatures", ["business_id"], unique=False)
    op.create_index(
        "ix_signatures_contract", "signatures", ["business_id", "contract_id"], unique=False
    )
    op.create_index(
        "ix_signatures_parent", "signatures", ["parent_type", "parent_id"], unique=False
    )
    op.create_table(
        "subjects",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('pet', 'vehicle', 'child', 'property')", name="ck_subjects_kind"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_subjects_business_client", "subjects", ["business_id", "client_id"], unique=False
    )
    op.create_index(op.f("ix_subjects_business_id"), "subjects", ["business_id"], unique=False)
    op.create_table(
        "threads",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('sms', 'email', 'chat')", name="ck_threads_channel"),
        sa.CheckConstraint("status IN ('open', 'closed')", name="ck_threads_status"),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "client_id", "channel", name="uq_threads_client_channel"
        ),
    )
    op.create_index(op.f("ix_threads_business_id"), "threads", ["business_id"], unique=False)
    op.create_index(
        "ix_threads_last_message", "threads", ["business_id", "last_message_at"], unique=False
    )
    op.create_table(
        "estimates",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("subtotal_cents", sa.BigInteger(), nullable=False),
        sa.Column("tax_total_cents", sa.BigInteger(), nullable=False),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("converted_invoice_id", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'accepted', 'declined', 'expired')",
            name="ck_estimates_status",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["converted_invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "number", name="uq_estimates_business_number"),
    )
    op.create_index(op.f("ix_estimates_business_id"), "estimates", ["business_id"], unique=False)
    op.create_index("ix_estimates_status", "estimates", ["business_id", "status"], unique=False)
    op.create_table(
        "gift_cards",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=True),
        sa.Column("initial_cents", sa.BigInteger(), nullable=False),
        sa.Column("balance_cents", sa.BigInteger(), nullable=False),
        sa.Column("purchaser_client_id", sa.String(), nullable=True),
        sa.Column("recipient", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'redeemed', 'expired', 'void')", name="ck_gift_cards_status"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchaser_client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "code", name="uq_gift_cards_business_code"),
    )
    op.create_index(op.f("ix_gift_cards_business_id"), "gift_cards", ["business_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("sender_user_id", sa.String(), nullable=True),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("broadcast_id", sa.String(), nullable=True),
        sa.Column("provider_ref", sa.String(), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("direction IN ('in', 'out')", name="ck_messages_direction"),
        sa.CheckConstraint(
            "status IN ('draft', 'queued', 'sent', 'delivered', 'read', 'failed')",
            name="ck_messages_status",
        ),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_broadcast", "messages", ["broadcast_id"], unique=False)
    op.create_index(op.f("ix_messages_business_id"), "messages", ["business_id"], unique=False)
    op.create_index("ix_messages_thread", "messages", ["thread_id", "created_at"], unique=False)
    op.create_table(
        "payments",
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("parent_payment_id", sa.String(), nullable=True),
        sa.Column("invoice_id", sa.String(), nullable=True),
        sa.Column("booking_id", sa.String(), nullable=True),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("provider_ref", sa.String(), nullable=True),
        sa.Column("reference_code", sa.String(), nullable=True),
        sa.Column("fee_cents", sa.BigInteger(), nullable=False),
        sa.Column("net_cents", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('payment', 'deposit', 'refund')", name="ck_payments_kind"),
        sa.CheckConstraint(
            "method IN ('card', 'interac', 'eft', 'cash', 'other')", name="ck_payments_method"
        ),
        sa.CheckConstraint(
            "provider IN ('stripe', 'interac', 'manual')", name="ck_payments_provider"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed', 'refunded', 'canceled')",
            name="ck_payments_status",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_business_id"), "payments", ["business_id"], unique=False)
    op.create_index("ix_payments_invoice", "payments", ["invoice_id"], unique=False)
    op.create_index("ix_payments_reference_code", "payments", ["reference_code"], unique=False)
    op.create_index("ix_payments_status", "payments", ["business_id", "status"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("staff_id", sa.String(), nullable=True),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("byday", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("until", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "frequency IN ('daily', 'weekly', 'monthly')", name="ck_schedules_frequency"
        ),
        sa.CheckConstraint("status IN ('active', 'ended', 'canceled')", name="ck_schedules_status"),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedules_business_id"), "schedules", ["business_id"], unique=False)
    op.create_index("ix_schedules_status", "schedules", ["business_id", "status"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_method_id", sa.String(), nullable=True),
        sa.Column("provider_ref", sa.String(), nullable=True),
        sa.Column("trial_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'canceled', 'past_due')", name="ck_subscriptions_status"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_business_id"), "subscriptions", ["business_id"], unique=False
    )
    op.create_index(
        "ix_subscriptions_client_status",
        "subscriptions",
        ["business_id", "client_id", "status"],
        unique=False,
    )
    op.create_table(
        "packages",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("sessions_total", sa.Integer(), nullable=False),
        sa.Column("sessions_used", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payment_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packages_business_id"), "packages", ["business_id"], unique=False)
    op.create_index(
        "ix_packages_client_status",
        "packages",
        ["business_id", "client_id", "status"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("staff_id", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("recurrence_id", sa.String(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("booked_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'canceled', 'completed')", name="ck_sessions_status"
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recurrence_id"],
            ["schedules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_business_id"), "sessions", ["business_id"], unique=False)
    op.create_index(
        "ix_sessions_business_start", "sessions", ["business_id", "starts_at"], unique=False
    )
    op.create_index(
        "ix_sessions_staff_start",
        "sessions",
        ["business_id", "staff_id", "starts_at"],
        unique=False,
    )
    op.create_table(
        "bookings",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("staff_id", sa.String(), nullable=True),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("subject_id", sa.String(), nullable=True),
        sa.Column("package_id", sa.String(), nullable=True),
        sa.Column("invoice_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column("deposit_required", sa.Boolean(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("source IN ('online', 'manual')", name="ck_bookings_source"),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'completed', 'canceled', 'no_show')",
            name="ck_bookings_status",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookings_business_id"), "bookings", ["business_id"], unique=False)
    op.create_index("ix_bookings_client", "bookings", ["business_id", "client_id"], unique=False)
    op.create_index("ix_bookings_session", "bookings", ["business_id", "session_id"], unique=False)
    op.create_index("ix_bookings_staff", "bookings", ["business_id", "staff_id"], unique=False)
    op.create_index("ix_bookings_status", "bookings", ["business_id", "status"], unique=False)
    op.create_table(
        "lines",
        sa.Column("parent_type", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=True),
        sa.Column("booking_id", sa.String(), nullable=True),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("unit_amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("tax_rate_id", sa.String(), nullable=True),
        sa.Column("tax_amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("parent_type IN ('invoice', 'estimate')", name="ck_lines_parent_type"),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_rate_id"],
            ["tax_rates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lines_business_id"), "lines", ["business_id"], unique=False)
    op.create_index("ix_lines_parent", "lines", ["parent_type", "parent_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("booking_id", sa.String(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("response", sa.String(), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_to_google", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('published', 'hidden', 'pending')", name="ck_reviews_status"
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_reviews_rating"),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_business_id"), "reviews", ["business_id"], unique=False)
    op.create_index(
        "ix_reviews_status_created",
        "reviews",
        ["business_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "review_requests",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("booking_id", sa.String(), nullable=True),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_count", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('sms', 'email')", name="ck_review_requests_channel"),
        sa.CheckConstraint(
            "status IN ('sent', 'opened', 'completed', 'expired')", name="ck_review_requests_status"
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_review_requests_token"),
    )
    op.create_index(
        op.f("ix_review_requests_business_id"), "review_requests", ["business_id"], unique=False
    )
    op.create_index(
        "ix_review_requests_status", "review_requests", ["business_id", "status"], unique=False
    )
    # Added after create_table to break the bookings/packages/payments FK cycle.
    op.create_foreign_key("fk_payments_booking", "payments", "bookings", ["booking_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_payments_booking", "payments", type_="foreignkey")
    op.drop_index("ix_review_requests_status", table_name="review_requests")
    op.drop_index(op.f("ix_review_requests_business_id"), table_name="review_requests")
    op.drop_table("review_requests")
    op.drop_index("ix_reviews_status_created", table_name="reviews")
    op.drop_index(op.f("ix_reviews_business_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_lines_parent", table_name="lines")
    op.drop_index(op.f("ix_lines_business_id"), table_name="lines")
    op.drop_table("lines")
    op.drop_index("ix_bookings_status", table_name="bookings")
    op.drop_index("ix_bookings_staff", table_name="bookings")
    op.drop_index("ix_bookings_session", table_name="bookings")
    op.drop_index("ix_bookings_client", table_name="bookings")
    op.drop_index(op.f("ix_bookings_business_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_sessions_staff_start", table_name="sessions")
    op.drop_index("ix_sessions_business_start", table_name="sessions")
    op.drop_index(op.f("ix_sessions_business_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_packages_client_status", table_name="packages")
    op.drop_index(op.f("ix_packages_business_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_index("ix_subscriptions_client_status", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_business_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_schedules_status", table_name="schedules")
    op.drop_index(op.f("ix_schedules_business_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index("ix_payments_status", table_name="payments")
    op.drop_index("ix_payments_reference_code", table_name="payments")
    op.drop_index("ix_payments_invoice", table_name="payments")
    op.drop_index(op.f("ix_payments_business_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_messages_thread", table_name="messages")
    op.drop_index(op.f("ix_messages_business_id"), table_name="messages")
    op.drop_index("ix_messages_broadcast", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_gift_cards_business_id"), table_name="gift_cards")
    op.drop_table("gift_cards")
    op.drop_index("ix_estimates_status", table_name="estimates")
    op.drop_index(op.f("ix_estimates_business_id"), table_name="estimates")
    op.drop_table("estimates")
    op.drop_index("ix_threads_last_message", table_name="threads")
    op.drop_index(op.f("ix_threads_business_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_subjects_business_id"), table_name="subjects")
    op.drop_index("ix_subjects_business_client", table_name="subjects")
    op.drop_table("subjects")
    op.drop_index("ix_signatures_parent", table_name="signatures")
    op.drop_index("ix_signatures_contract", table_name="signatures")
    op.drop_index(op.f("ix_signatures_business_id"), table_name="signatures")
    op.drop_table("signatures")
    op.drop_index(op.f("ix_payout_allocations_business_id"), table_name="payout_allocations")
    op.drop_index("ix_payout_alloc_staff", table_name="payout_allocations")
    op.drop_index("ix_payout_alloc_source", table_name="payout_allocations")
    op.drop_table("payout_allocations")
    op.drop_index("ix_payment_methods_client", table_name="payment_methods")
    op.drop_index(op.f("ix_payment_methods_business_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    op.drop_index("ix_items_business_kind_active", table_name="items")
    op.drop_index(op.f("ix_items_business_id"), table_name="items")
    op.drop_table("items")
    op.drop_index("ix_invoices_status", table_name="invoices")
    op.drop_index("ix_invoices_client", table_name="invoices")
    op.drop_index(op.f("ix_invoices_business_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_form_responses_parent", table_name="form_responses")
    op.drop_index("ix_form_responses_form", table_name="form_responses")
    op.drop_index(op.f("ix_form_responses_business_id"), table_name="form_responses")
    op.drop_table("form_responses")
    op.drop_index("ix_form_fields_form", table_name="form_fields")
    op.drop_index(op.f("ix_form_fields_business_id"), table_name="form_fields")
    op.drop_table("form_fields")
    op.drop_index("ix_availability_staff", table_name="availability")
    op.drop_index(op.f("ix_availability_business_id"), table_name="availability")
    op.drop_table("availability")
    op.drop_index("ix_tax_rates_province", table_name="tax_rates")
    op.drop_index(op.f("ix_tax_rates_business_id"), table_name="tax_rates")
    op.drop_table("tax_rates")
    op.drop_index(op.f("ix_staff_business_id"), table_name="staff")
    op.drop_table("staff")
    op.drop_index(op.f("ix_resources_business_id"), table_name="resources")
    op.drop_table("resources")
    op.drop_index("ix_payouts_status", table_name="payouts")
    op.drop_index(op.f("ix_payouts_business_id"), table_name="payouts")
    op.drop_table("payouts")
    op.drop_index("ix_notes_parent", table_name="notes")
    op.drop_index(op.f("ix_notes_business_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_forms_business_id"), table_name="forms")
    op.drop_table("forms")
    op.drop_index("ix_files_parent", table_name="files")
    op.drop_index(op.f("ix_files_business_id"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_contracts_business_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index("ix_clients_business_phone", table_name="clients")
    op.drop_index(op.f("ix_clients_business_id"), table_name="clients")
    op.drop_index("ix_clients_business_email", table_name="clients")
    op.drop_table("clients")
    op.drop_index("ix_broadcasts_status", table_name="broadcasts")
    op.drop_index(op.f("ix_broadcasts_business_id"), table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index(op.f("ix_audit_logs_business_id"), table_name="audit_logs")
    op.drop_index("ix_audit_entity", table_name="audit_logs")
    op.drop_index("ix_audit_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_webhook_provider_status", table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_table("users")
    op.drop_table("businesses")
    # ### end Alembic commands ###
